In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/APi.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2015-12-29,371.0,381.0,368.0,372.0,NaN,13555.0,5029450.0,0
1,2015-12-31,372.0,381.0,368.0,370.0,-0.54,11336.0,4216637.0,0
2,2016-01-03,370.0,377.0,362.0,369.0,-0.27,11849.0,4375998.0,0
3,2016-01-04,369.0,373.0,358.0,368.0,-0.27,9183.0,3351712.0,0
4,2016-01-05,368.0,375.0,350.0,375.0,1.90,27876.0,10117332.0,0
...,...,...,...,...,...,...,...,...,...
2325,2026-02-24,291.9,299.0,291.9,297.0,-0.27,116135.0,34478375.2,1
2326,2026-02-25,300.7,304.0,295.0,302.0,1.68,271738.0,81394139.6,1
2327,2026-02-26,296.9,315.0,296.9,312.4,3.44,1054543.0,326832574.0,1
2328,2026-03-01,312.4,321.0,308.0,316.0,1.15,1049844.0,332175622.1,1
2329,2026-03-03,316.0,319.0,312.2,317.0,0.32,483492.0,152908907.9,1

In [3]:

# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [4]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,status
0,2015-12-29,371.0,381.0,368.0,372.0,NaN,13555.0,5029450.0,0
1,2015-12-31,372.0,381.0,368.0,370.0,-0.54,11336.0,4216637.0,0
2,2016-01-03,370.0,377.0,362.0,369.0,-0.27,11849.0,4375998.0,0
3,2016-01-04,369.0,373.0,358.0,368.0,-0.27,9183.0,3351712.0,0
4,2016-01-05,368.0,375.0,350.0,375.0,1.90,27876.0,10117332.0,0
...,...,...,...,...,...,...,...,...,...
2325,2026-02-24,291.9,299.0,291.9,297.0,-0.27,116135.0,34478375.2,1
2326,2026-02-25,300.7,304.0,295.0,302.0,1.68,271738.0,81394139.6,1
2327,2026-02-26,296.9,315.0,296.9,312.4,3.44,1054543.0,326832574.0,1
2328,2026-03-01,312.4,321.0,308.0,316.0,1.15,1049844.0,332175622.1,1
2329,2026-03-03,316.0,319.0,312.2,317.0,0.32,483492.0,152908907.9,1

In [5]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:

#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [7]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,status,year
0,2023-01-01,236.0,240.9,228.4,235.0,1.25,325636.0,76939033.9,-1,2023
1,2023-01-02,235.0,241.2,230.0,237.0,0.85,143592.0,34090444.2,1,2023
2,2023-01-03,235.0,244.7,233.3,238.0,0.42,187018.0,44691834.5,1,2023
3,2023-01-04,238.0,246.7,237.3,246.2,3.45,238825.0,57714485.8,1,2023
4,2023-01-05,249.9,260.0,244.0,254.9,3.53,324170.0,81341205.7,1,2023
...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,291.9,299.0,291.9,297.0,-0.27,116135.0,34478375.2,1,2026
719,2026-02-25,300.7,304.0,295.0,302.0,1.68,271738.0,81394139.6,1,2026
720,2026-02-26,296.9,315.0,296.9,312.4,3.44,1054543.0,326832574.0,1,2026
721,2026-03-01,312.4,321.0,308.0,316.0,1.15,1049844.0,332175622.1,1,2026
722,2026-03-03,316.0,319.0,312.2,317.0,0.32,483492.0,152908907.9,1,2026

In [8]:
df.drop(columns = 'status', inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,236.0,240.9,228.4,235.0,1.25,325636.0,76939033.9,2023
1,2023-01-02,235.0,241.2,230.0,237.0,0.85,143592.0,34090444.2,2023
2,2023-01-03,235.0,244.7,233.3,238.0,0.42,187018.0,44691834.5,2023
3,2023-01-04,238.0,246.7,237.3,246.2,3.45,238825.0,57714485.8,2023
4,2023-01-05,249.9,260.0,244.0,254.9,3.53,324170.0,81341205.7,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,291.9,299.0,291.9,297.0,-0.27,116135.0,34478375.2,2026
719,2026-02-25,300.7,304.0,295.0,302.0,1.68,271738.0,81394139.6,2026
720,2026-02-26,296.9,315.0,296.9,312.4,3.44,1054543.0,326832574.0,2026
721,2026-03-01,312.4,321.0,308.0,316.0,1.15,1049844.0,332175622.1,2026
722,2026-03-03,316.0,319.0,312.2,317.0,0.32,483492.0,152908907.9,2026

In [9]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # FY 78/79 to 81/82
    'eps': [4.85, 3.63, 7.51, 14.03],    # NPR (Annualized EPS, adjusted for capital dilution)
    'pe-ratio': [38.50, 42.10, 35.80, 24.15], # Market price volatility vs earnings growth
    'roe': [4.52, 3.45, 6.88, 12.15],    # Return on Equity (%)
    'dividend': [7.50, 0.00, 5.00, 5.26], # Total % (Bonus + Cash)
    'net-margin': [22.45, 18.12, 36.50, 44.50], # (%)
    'pb-ratio': [1.85, 1.95, 2.45, 2.75],     # Price-to-Book Ratio
    'debt-equity': [1.15, 1.58, 0.90, 0.85]} # Gearing ratio (Total Debt/Equity)

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022   4.85     38.50   4.52      7.50       22.45      1.85         1.15
1  2023   3.63     42.10   3.45      0.00       18.12      1.95         1.58
2  2024   7.51     35.80   6.88      5.00       36.50      2.45         0.90
3  2025  14.03     24.15  12.15      5.26       44.50      2.75         0.85

In [10]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2023-01-01,236.0,240.9,228.4,235.0,1.25,325636.0,76939033.9,2023,3.63,42.1,3.45,0.0,18.12,1.95,1.58
1,2023-01-02,235.0,241.2,230.0,237.0,0.85,143592.0,34090444.2,2023,3.63,42.1,3.45,0.0,18.12,1.95,1.58
2,2023-01-03,235.0,244.7,233.3,238.0,0.42,187018.0,44691834.5,2023,3.63,42.1,3.45,0.0,18.12,1.95,1.58
3,2023-01-04,238.0,246.7,237.3,246.2,3.45,238825.0,57714485.8,2023,3.63,42.1,3.45,0.0,18.12,1.95,1.58
4,2023-01-05,249.9,260.0,244.0,254.9,3.53,324170.0,81341205.7,2023,3.63,42.1,3.45,0.0,18.12,1.95,1.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,291.9,299.0,291.9,297.0,-0.27,116135.0,34478375.2,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,2026-02-25,300.7,304.0,295.0,302.0,1.68,271738.0,81394139.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,2026-02-26,296.9,315.0,296.9,312.4,3.44,1054543.0,326832574.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,2026-03-01,312.4,321.0,308.0,316.0,1.15,1049844.0,332175622.1,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,2026-03-03,316.0,319.0,312.2,317.0,0.32,483492.0,152908907.9,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/API.csv', index = False)