In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/BARUN.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2015-10-28,388.0,426.0,395.0,419.0,NaN,5200.0,2161590.0,0
1,2015-10-29,419.0,422.0,400.0,412.0,-1.67,4740.0,1908510.0,0
2,2015-11-01,412.0,410.0,391.0,400.0,-2.91,2670.0,1059460.0,0
3,2015-11-02,400.0,397.0,385.0,385.0,-3.75,1800.0,703800.0,0
4,2015-11-03,385.0,378.0,357.0,368.0,-4.42,620.0,226400.0,0
...,...,...,...,...,...,...,...,...,...
2267,2026-02-09,375.0,375.0,358.0,363.9,-1.03,298000.0,107914538.0,-1
2268,2026-02-10,363.9,369.8,356.0,358.0,-1.62,192605.0,69513469.3,-1
2269,2026-02-11,365.1,368.2,358.0,368.0,2.79,138625.0,50314531.2,1
2270,2026-02-12,373.9,377.1,364.0,365.2,-0.76,193036.0,71550490.2,-1
2271,2026-02-16,365.2,372.0,358.0,359.0,-1.70,92498.0,33483631.3,-1

In [3]:
#dropping the status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2015-10-28,388.0,426.0,395.0,419.0,NaN,5200.0,2161590.0
1,2015-10-29,419.0,422.0,400.0,412.0,-1.67,4740.0,1908510.0
2,2015-11-01,412.0,410.0,391.0,400.0,-2.91,2670.0,1059460.0
3,2015-11-02,400.0,397.0,385.0,385.0,-3.75,1800.0,703800.0
4,2015-11-03,385.0,378.0,357.0,368.0,-4.42,620.0,226400.0
...,...,...,...,...,...,...,...,...
2267,2026-02-09,375.0,375.0,358.0,363.9,-1.03,298000.0,107914538.0
2268,2026-02-10,363.9,369.8,356.0,358.0,-1.62,192605.0,69513469.3
2269,2026-02-11,365.1,368.2,358.0,368.0,2.79,138625.0,50314531.2
2270,2026-02-12,373.9,377.1,364.0,365.2,-0.76,193036.0,71550490.2
2271,2026-02-16,365.2,372.0,358.0,359.0,-1.70,92498.0,33483631.3

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2015-10-28,388.0,426.0,395.0,419.0,NaN,5200.0,2161590.0
1,2015-10-29,419.0,422.0,400.0,412.0,-1.67,4740.0,1908510.0
2,2015-11-01,412.0,410.0,391.0,400.0,-2.91,2670.0,1059460.0
3,2015-11-02,400.0,397.0,385.0,385.0,-3.75,1800.0,703800.0
4,2015-11-03,385.0,378.0,357.0,368.0,-4.42,620.0,226400.0
...,...,...,...,...,...,...,...,...
2267,2026-02-09,375.0,375.0,358.0,363.9,-1.03,298000.0,107914538.0
2268,2026-02-10,363.9,369.8,356.0,358.0,-1.62,192605.0,69513469.3
2269,2026-02-11,365.1,368.2,358.0,368.0,2.79,138625.0,50314531.2
2270,2026-02-12,373.9,377.1,364.0,365.2,-0.76,193036.0,71550490.2
2271,2026-02-16,365.2,372.0,358.0,359.0,-1.70,92498.0,33483631.3

In [6]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2015-10-28,388.0,426.0,395.0,419.0,NaN,5200.0,2161590.0,2015
1,2015-10-29,419.0,422.0,400.0,412.0,-1.67,4740.0,1908510.0,2015
2,2015-11-01,412.0,410.0,391.0,400.0,-2.91,2670.0,1059460.0,2015
3,2015-11-02,400.0,397.0,385.0,385.0,-3.75,1800.0,703800.0,2015
4,2015-11-03,385.0,378.0,357.0,368.0,-4.42,620.0,226400.0,2015
...,...,...,...,...,...,...,...,...,...
2267,2026-02-09,375.0,375.0,358.0,363.9,-1.03,298000.0,107914538.0,2026
2268,2026-02-10,363.9,369.8,356.0,358.0,-1.62,192605.0,69513469.3,2026
2269,2026-02-11,365.1,368.2,358.0,368.0,2.79,138625.0,50314531.2,2026
2270,2026-02-12,373.9,377.1,364.0,365.2,-0.76,193036.0,71550490.2,2026
2271,2026-02-16,365.2,372.0,358.0,359.0,-1.70,92498.0,33483631.3,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
1557,2023-01-01,222.4,234.0,216.0,227.0,3.18,53966.0,12222885.8,2023
1558,2023-01-02,222.9,228.0,222.1,228.0,0.44,24685.0,5575119.9,2023
1559,2023-01-03,230.0,233.0,224.0,225.6,-1.05,32840.0,7503033.2,2023
1560,2023-01-04,230.1,239.0,226.2,238.0,5.50,34727.0,8023337.0,2023
1561,2023-01-05,240.0,244.2,232.4,241.1,1.30,65827.0,15773086.9,2023
...,...,...,...,...,...,...,...,...,...
2267,2026-02-09,375.0,375.0,358.0,363.9,-1.03,298000.0,107914538.0,2026
2268,2026-02-10,363.9,369.8,356.0,358.0,-1.62,192605.0,69513469.3,2026
2269,2026-02-11,365.1,368.2,358.0,368.0,2.79,138625.0,50314531.2,2026
2270,2026-02-12,373.9,377.1,364.0,365.2,-0.76,193036.0,71550490.2,2026
2271,2026-02-16,365.2,372.0,358.0,359.0,-1.70,92498.0,33483631.3,2026

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,222.4,234.0,216.0,227.0,3.18,53966.0,12222885.8,2023
1,2023-01-02,222.9,228.0,222.1,228.0,0.44,24685.0,5575119.9,2023
2,2023-01-03,230.0,233.0,224.0,225.6,-1.05,32840.0,7503033.2,2023
3,2023-01-04,230.1,239.0,226.2,238.0,5.50,34727.0,8023337.0,2023
4,2023-01-05,240.0,244.2,232.4,241.1,1.30,65827.0,15773086.9,2023
...,...,...,...,...,...,...,...,...,...
710,2026-02-09,375.0,375.0,358.0,363.9,-1.03,298000.0,107914538.0,2026
711,2026-02-10,363.9,369.8,356.0,358.0,-1.62,192605.0,69513469.3,2026
712,2026-02-11,365.1,368.2,358.0,368.0,2.79,138625.0,50314531.2,2026
713,2026-02-12,373.9,377.1,364.0,365.2,-0.76,193036.0,71550490.2,2026
714,2026-02-16,365.2,372.0,358.0,359.0,-1.70,92498.0,33483631.3,2026

In [11]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [12.18, 1.55, 3.02, 7.25],
    'pe-ratio': [38.50, 185.20, 115.40, 50.30],
    'roe': [11.45, 1.48, 2.95, 6.96],
    'dividend': [0.00, 0.00, 0.00, 5.00]}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend
0  2022  12.18      38.5  11.45       0.0
1  2023   1.55     185.2   1.48       0.0
2  2024   3.02     115.4   2.95       0.0
3  2025   7.25      50.3   6.96       5.0

In [12]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2023-01-01,222.4,234.0,216.0,227.0,3.18,53966.0,12222885.8,2023,1.55,185.2,1.48,0.0
1,2023-01-02,222.9,228.0,222.1,228.0,0.44,24685.0,5575119.9,2023,1.55,185.2,1.48,0.0
2,2023-01-03,230.0,233.0,224.0,225.6,-1.05,32840.0,7503033.2,2023,1.55,185.2,1.48,0.0
3,2023-01-04,230.1,239.0,226.2,238.0,5.50,34727.0,8023337.0,2023,1.55,185.2,1.48,0.0
4,2023-01-05,240.0,244.2,232.4,241.1,1.30,65827.0,15773086.9,2023,1.55,185.2,1.48,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
710,2026-02-09,375.0,375.0,358.0,363.9,-1.03,298000.0,107914538.0,2026,NaN,NaN,NaN,NaN
711,2026-02-10,363.9,369.8,356.0,358.0,-1.62,192605.0,69513469.3,2026,NaN,NaN,NaN,NaN
712,2026-02-11,365.1,368.2,358.0,368.0,2.79,138625.0,50314531.2,2026,NaN,NaN,NaN,NaN
713,2026-02-12,373.9,377.1,364.0,365.2,-0.76,193036.0,71550490.2,2026,NaN,NaN,NaN,NaN
714,2026-02-16,365.2,372.0,358.0,359.0,-1.70,92498.0,33483631.3,2026,NaN,NaN,NaN,NaN

In [13]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/BARUN.csv', index = False)