In [3]:
#importing the pandas library
import pandas as pd

In [4]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/BPCL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2005-01-20,480.0,280.0,250.0,280.0,NaN,4230.0,0.0,0
1,2005-01-21,280.0,328.0,294.0,328.0,17.14,70.0,0.0,0
2,2005-01-24,328.0,371.0,344.0,371.0,13.11,50.0,0.0,0
3,2005-01-25,371.0,427.0,389.0,427.0,15.09,140.0,0.0,0
4,2005-01-26,427.0,465.0,448.0,465.0,8.90,500.0,0.0,0
...,...,...,...,...,...,...,...,...,...
3625,2026-02-24,695.0,723.0,695.0,704.9,0.84,35037.0,24604711.7,1
3626,2026-02-25,700.0,717.0,700.0,710.0,0.72,51706.0,36565043.7,1
3627,2026-02-26,695.9,749.0,682.0,713.0,0.42,108908.0,78339792.4,1
3628,2026-03-01,699.0,718.0,699.0,715.0,0.28,33235.0,23664766.3,1
3629,2026-03-03,700.9,734.0,700.9,733.0,2.52,68318.0,49652445.1,1

In [5]:
#dropping status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2005-01-20,480.0,280.0,250.0,280.0,NaN,4230.0,0.0
1,2005-01-21,280.0,328.0,294.0,328.0,17.14,70.0,0.0
2,2005-01-24,328.0,371.0,344.0,371.0,13.11,50.0,0.0
3,2005-01-25,371.0,427.0,389.0,427.0,15.09,140.0,0.0
4,2005-01-26,427.0,465.0,448.0,465.0,8.90,500.0,0.0
...,...,...,...,...,...,...,...,...
3625,2026-02-24,695.0,723.0,695.0,704.9,0.84,35037.0,24604711.7
3626,2026-02-25,700.0,717.0,700.0,710.0,0.72,51706.0,36565043.7
3627,2026-02-26,695.9,749.0,682.0,713.0,0.42,108908.0,78339792.4
3628,2026-03-01,699.0,718.0,699.0,715.0,0.28,33235.0,23664766.3
3629,2026-03-03,700.9,734.0,700.9,733.0,2.52,68318.0,49652445.1

In [6]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [7]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [8]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2005-01-20,480.0,280.0,250.0,280.0,NaN,4230.0,0.0,2005
1,2005-01-21,280.0,328.0,294.0,328.0,17.14,70.0,0.0,2005
2,2005-01-24,328.0,371.0,344.0,371.0,13.11,50.0,0.0,2005
3,2005-01-25,371.0,427.0,389.0,427.0,15.09,140.0,0.0,2005
4,2005-01-26,427.0,465.0,448.0,465.0,8.90,500.0,0.0,2005
...,...,...,...,...,...,...,...,...,...
3625,2026-02-24,695.0,723.0,695.0,704.9,0.84,35037.0,24604711.7,2026
3626,2026-02-25,700.0,717.0,700.0,710.0,0.72,51706.0,36565043.7,2026
3627,2026-02-26,695.9,749.0,682.0,713.0,0.42,108908.0,78339792.4,2026
3628,2026-03-01,699.0,718.0,699.0,715.0,0.28,33235.0,23664766.3,2026
3629,2026-03-03,700.9,734.0,700.9,733.0,2.52,68318.0,49652445.1,2026

In [9]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [10]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2665,2022-01-02,415.0,416.0,410.0,415.0,0.00,10830.0,4473113.3,2022
2666,2022-01-03,415.0,419.9,414.0,418.0,0.72,13872.0,5770963.2,2022
2667,2022-01-04,412.0,425.0,410.0,424.0,1.44,15929.0,6685849.1,2022
2668,2022-01-05,430.0,445.0,421.4,425.0,0.24,25832.0,11095196.0,2022
2669,2022-01-06,420.0,433.0,420.0,430.9,1.39,13157.0,5636316.3,2022
...,...,...,...,...,...,...,...,...,...
3625,2026-02-24,695.0,723.0,695.0,704.9,0.84,35037.0,24604711.7,2026
3626,2026-02-25,700.0,717.0,700.0,710.0,0.72,51706.0,36565043.7,2026
3627,2026-02-26,695.9,749.0,682.0,713.0,0.42,108908.0,78339792.4,2026
3628,2026-03-01,699.0,718.0,699.0,715.0,0.28,33235.0,23664766.3,2026
3629,2026-03-03,700.9,734.0,700.9,733.0,2.52,68318.0,49652445.1,2026

In [11]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,415.0,416.0,410.0,415.0,0.00,10830.0,4473113.3,2022
1,2022-01-03,415.0,419.9,414.0,418.0,0.72,13872.0,5770963.2,2022
2,2022-01-04,412.0,425.0,410.0,424.0,1.44,15929.0,6685849.1,2022
3,2022-01-05,430.0,445.0,421.4,425.0,0.24,25832.0,11095196.0,2022
4,2022-01-06,420.0,433.0,420.0,430.9,1.39,13157.0,5636316.3,2022
...,...,...,...,...,...,...,...,...,...
960,2026-02-24,695.0,723.0,695.0,704.9,0.84,35037.0,24604711.7,2026
961,2026-02-25,700.0,717.0,700.0,710.0,0.72,51706.0,36565043.7,2026
962,2026-02-26,695.9,749.0,682.0,713.0,0.42,108908.0,78339792.4,2026
963,2026-03-01,699.0,718.0,699.0,715.0,0.28,33235.0,23664766.3,2026
964,2026-03-03,700.9,734.0,700.9,733.0,2.52,68318.0,49652445.1,2026

In [12]:
#adding some fundamental signals
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [8.05, 8.24, 8.13, 9.95],      # Highly stable income from PPA
    'pe-ratio': [38.20, 41.10, 52.40, 78.57], # P/E spiked in 2025 due to market speculation
    'roe': [4.50, 4.70, 4.30, 4.80],      # Very low ROE due to huge reserves
    'dividend': [12.50, 5.00, 5.00, 6.00]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year   eps  pe-ratio  roe  dividend
0  2022  8.05     38.20  4.5      12.5
1  2023  8.24     41.10  4.7       5.0
2  2024  8.13     52.40  4.3       5.0
3  2025  9.95     78.57  4.8       6.0

In [13]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2022-01-02,415.0,416.0,410.0,415.0,0.00,10830.0,4473113.3,2022,8.05,38.2,4.5,12.5
1,2022-01-03,415.0,419.9,414.0,418.0,0.72,13872.0,5770963.2,2022,8.05,38.2,4.5,12.5
2,2022-01-04,412.0,425.0,410.0,424.0,1.44,15929.0,6685849.1,2022,8.05,38.2,4.5,12.5
3,2022-01-05,430.0,445.0,421.4,425.0,0.24,25832.0,11095196.0,2022,8.05,38.2,4.5,12.5
4,2022-01-06,420.0,433.0,420.0,430.9,1.39,13157.0,5636316.3,2022,8.05,38.2,4.5,12.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,2026-02-24,695.0,723.0,695.0,704.9,0.84,35037.0,24604711.7,2026,NaN,NaN,NaN,NaN
961,2026-02-25,700.0,717.0,700.0,710.0,0.72,51706.0,36565043.7,2026,NaN,NaN,NaN,NaN
962,2026-02-26,695.9,749.0,682.0,713.0,0.42,108908.0,78339792.4,2026,NaN,NaN,NaN,NaN
963,2026-03-01,699.0,718.0,699.0,715.0,0.28,33235.0,23664766.3,2026,NaN,NaN,NaN,NaN
964,2026-03-03,700.9,734.0,700.9,733.0,2.52,68318.0,49652445.1,2026,NaN,NaN,NaN,NaN

In [14]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/BPCL.csv', index = False)