In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/processed_data/CHL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0,0
1,2017-09-18,159.0,165.0,157.0,163.0,2.52,603.0,97469.0,0
2,2017-09-20,163.0,165.0,161.0,161.0,-1.23,131.0,21205.0,0
3,2017-09-24,161.0,163.0,158.0,163.0,1.24,618.0,99240.0,0
4,2017-09-25,163.0,169.0,166.0,169.0,3.68,80.0,13490.0,0
...,...,...,...,...,...,...,...,...,...
1857,2026-01-26,285.0,294.6,282.1,286.0,-1.00,119421.0,34304006.6,1
1858,2026-01-27,291.6,295.0,277.1,279.0,-2.45,153123.0,43739384.9,-1
1859,2026-01-28,278.0,286.9,275.4,282.9,1.40,84154.0,23601104.7,1
1860,2026-01-29,288.0,297.8,285.1,287.0,1.45,195608.0,57218138.0,-1
1861,2026-02-01,285.0,292.7,282.0,283.0,-1.39,60974.0,17411496.8,-1

In [3]:
#dropping the status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0
1,2017-09-18,159.0,165.0,157.0,163.0,2.52,603.0,97469.0
2,2017-09-20,163.0,165.0,161.0,161.0,-1.23,131.0,21205.0
3,2017-09-24,161.0,163.0,158.0,163.0,1.24,618.0,99240.0
4,2017-09-25,163.0,169.0,166.0,169.0,3.68,80.0,13490.0
...,...,...,...,...,...,...,...,...
1857,2026-01-26,285.0,294.6,282.1,286.0,-1.00,119421.0,34304006.6
1858,2026-01-27,291.6,295.0,277.1,279.0,-2.45,153123.0,43739384.9
1859,2026-01-28,278.0,286.9,275.4,282.9,1.40,84154.0,23601104.7
1860,2026-01-29,288.0,297.8,285.1,287.0,1.45,195608.0,57218138.0
1861,2026-02-01,285.0,292.7,282.0,283.0,-1.39,60974.0,17411496.8

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0
1,2017-09-18,159.0,165.0,157.0,163.0,2.52,603.0,97469.0
2,2017-09-20,163.0,165.0,161.0,161.0,-1.23,131.0,21205.0
3,2017-09-24,161.0,163.0,158.0,163.0,1.24,618.0,99240.0
4,2017-09-25,163.0,169.0,166.0,169.0,3.68,80.0,13490.0
...,...,...,...,...,...,...,...,...
1857,2026-01-26,285.0,294.6,282.1,286.0,-1.00,119421.0,34304006.6
1858,2026-01-27,291.6,295.0,277.1,279.0,-2.45,153123.0,43739384.9
1859,2026-01-28,278.0,286.9,275.4,282.9,1.40,84154.0,23601104.7
1860,2026-01-29,288.0,297.8,285.1,287.0,1.45,195608.0,57218138.0
1861,2026-02-01,285.0,292.7,282.0,283.0,-1.39,60974.0,17411496.8

In [5]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0,2017
1,2017-09-18,159.0,165.0,157.0,163.0,2.52,603.0,97469.0,2017
2,2017-09-20,163.0,165.0,161.0,161.0,-1.23,131.0,21205.0,2017
3,2017-09-24,161.0,163.0,158.0,163.0,1.24,618.0,99240.0,2017
4,2017-09-25,163.0,169.0,166.0,169.0,3.68,80.0,13490.0,2017
...,...,...,...,...,...,...,...,...,...
1857,2026-01-26,285.0,294.6,282.1,286.0,-1.00,119421.0,34304006.6,2026
1858,2026-01-27,291.6,295.0,277.1,279.0,-2.45,153123.0,43739384.9,2026
1859,2026-01-28,278.0,286.9,275.4,282.9,1.40,84154.0,23601104.7,2026
1860,2026-01-29,288.0,297.8,285.1,287.0,1.45,195608.0,57218138.0,2026
1861,2026-02-01,285.0,292.7,282.0,283.0,-1.39,60974.0,17411496.8,2026

In [6]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
915,2022-01-02,475.0,478.0,461.0,474.0,0.85,17920.0,8373360.1,2022
916,2022-01-03,480.0,480.0,463.1,474.8,0.17,10012.0,4713185.8,2022
917,2022-01-04,484.0,490.0,474.6,485.0,2.15,81879.0,39587292.3,2022
918,2022-01-05,396.0,434.0,396.0,417.9,5.49,34255.0,14251486.8,2022
919,2022-01-06,426.0,426.0,411.0,417.8,-0.02,10540.0,4378301.3,2022
...,...,...,...,...,...,...,...,...,...
1838,2025-12-23,253.8,253.8,245.0,248.0,-0.80,30957.0,7682622.2,2025
1839,2025-12-24,250.0,257.9,249.1,254.0,2.42,21130.0,5313199.0,2025
1840,2025-12-28,258.0,261.0,253.6,260.1,2.40,46653.0,12009125.5,2025
1841,2025-12-29,260.0,263.0,254.3,254.3,-2.23,25215.0,6497490.0,2025
1842,2025-12-31,250.4,264.0,250.4,261.0,2.63,55493.0,14474287.5,2025

In [7]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,475.0,478.0,461.0,474.0,0.85,17920.0,8373360.1,2022
1,2022-01-03,480.0,480.0,463.1,474.8,0.17,10012.0,4713185.8,2022
2,2022-01-04,484.0,490.0,474.6,485.0,2.15,81879.0,39587292.3,2022
3,2022-01-05,396.0,434.0,396.0,417.9,5.49,34255.0,14251486.8,2022
4,2022-01-06,426.0,426.0,411.0,417.8,-0.02,10540.0,4378301.3,2022
...,...,...,...,...,...,...,...,...,...
923,2025-12-23,253.8,253.8,245.0,248.0,-0.80,30957.0,7682622.2,2025
924,2025-12-24,250.0,257.9,249.1,254.0,2.42,21130.0,5313199.0,2025
925,2025-12-28,258.0,261.0,253.6,260.1,2.40,46653.0,12009125.5,2025
926,2025-12-29,260.0,263.0,254.3,254.3,-2.23,25215.0,6497490.0,2025
927,2025-12-31,250.4,264.0,250.4,261.0,2.63,55493.0,14474287.5,2025