In [8]:
#importing the pandas library
import pandas as pd

In [9]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/CHL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0,0
1,2017-09-18,159.0,165.0,157.0,163.0,2.52,603.0,97469.0,0
2,2017-09-20,163.0,165.0,161.0,161.0,-1.23,131.0,21205.0,0
3,2017-09-24,161.0,163.0,158.0,163.0,1.24,618.0,99240.0,0
4,2017-09-25,163.0,169.0,166.0,169.0,3.68,80.0,13490.0,0
...,...,...,...,...,...,...,...,...,...
1875,2026-02-24,274.0,276.4,270.0,275.0,2.23,33131.0,9097005.7,1
1876,2026-02-25,275.0,281.8,275.0,280.0,1.82,28569.0,7993722.2,1
1877,2026-02-26,280.0,283.0,278.0,282.7,0.96,32485.0,9151407.2,1
1878,2026-03-01,278.0,286.0,277.1,284.1,0.50,37223.0,10535068.8,1
1879,2026-03-03,283.0,292.0,283.0,289.9,2.04,44798.0,12924128.5,1

In [10]:
#dropping the status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0
1,2017-09-18,159.0,165.0,157.0,163.0,2.52,603.0,97469.0
2,2017-09-20,163.0,165.0,161.0,161.0,-1.23,131.0,21205.0
3,2017-09-24,161.0,163.0,158.0,163.0,1.24,618.0,99240.0
4,2017-09-25,163.0,169.0,166.0,169.0,3.68,80.0,13490.0
...,...,...,...,...,...,...,...,...
1875,2026-02-24,274.0,276.4,270.0,275.0,2.23,33131.0,9097005.7
1876,2026-02-25,275.0,281.8,275.0,280.0,1.82,28569.0,7993722.2
1877,2026-02-26,280.0,283.0,278.0,282.7,0.96,32485.0,9151407.2
1878,2026-03-01,278.0,286.0,277.1,284.1,0.50,37223.0,10535068.8
1879,2026-03-03,283.0,292.0,283.0,289.9,2.04,44798.0,12924128.5

In [11]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0
1,2017-09-18,159.0,165.0,157.0,163.0,2.52,603.0,97469.0
2,2017-09-20,163.0,165.0,161.0,161.0,-1.23,131.0,21205.0
3,2017-09-24,161.0,163.0,158.0,163.0,1.24,618.0,99240.0
4,2017-09-25,163.0,169.0,166.0,169.0,3.68,80.0,13490.0
...,...,...,...,...,...,...,...,...
1875,2026-02-24,274.0,276.4,270.0,275.0,2.23,33131.0,9097005.7
1876,2026-02-25,275.0,281.8,275.0,280.0,1.82,28569.0,7993722.2
1877,2026-02-26,280.0,283.0,278.0,282.7,0.96,32485.0,9151407.2
1878,2026-03-01,278.0,286.0,277.1,284.1,0.50,37223.0,10535068.8
1879,2026-03-03,283.0,292.0,283.0,289.9,2.04,44798.0,12924128.5

In [12]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0,2017
1,2017-09-18,159.0,165.0,157.0,163.0,2.52,603.0,97469.0,2017
2,2017-09-20,163.0,165.0,161.0,161.0,-1.23,131.0,21205.0,2017
3,2017-09-24,161.0,163.0,158.0,163.0,1.24,618.0,99240.0,2017
4,2017-09-25,163.0,169.0,166.0,169.0,3.68,80.0,13490.0,2017
...,...,...,...,...,...,...,...,...,...
1875,2026-02-24,274.0,276.4,270.0,275.0,2.23,33131.0,9097005.7,2026
1876,2026-02-25,275.0,281.8,275.0,280.0,1.82,28569.0,7993722.2,2026
1877,2026-02-26,280.0,283.0,278.0,282.7,0.96,32485.0,9151407.2,2026
1878,2026-03-01,278.0,286.0,277.1,284.1,0.50,37223.0,10535068.8,2026
1879,2026-03-03,283.0,292.0,283.0,289.9,2.04,44798.0,12924128.5,2026

In [13]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
1157,2023-01-01,238.0,260.0,238.0,247.5,3.99,30723.0,7661870.9,2023
1158,2023-01-02,243.0,260.1,240.0,260.0,5.05,30548.0,7724791.4,2023
1159,2023-01-03,263.0,267.0,253.0,254.0,-2.31,18165.0,4658482.0,2023
1160,2023-01-04,250.0,272.0,250.0,268.0,5.51,19898.0,5278879.5,2023
1161,2023-01-05,273.3,281.0,263.0,274.9,2.57,15850.0,4303330.3,2023
...,...,...,...,...,...,...,...,...,...
1875,2026-02-24,274.0,276.4,270.0,275.0,2.23,33131.0,9097005.7,2026
1876,2026-02-25,275.0,281.8,275.0,280.0,1.82,28569.0,7993722.2,2026
1877,2026-02-26,280.0,283.0,278.0,282.7,0.96,32485.0,9151407.2,2026
1878,2026-03-01,278.0,286.0,277.1,284.1,0.50,37223.0,10535068.8,2026
1879,2026-03-03,283.0,292.0,283.0,289.9,2.04,44798.0,12924128.5,2026

In [14]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,238.0,260.0,238.0,247.5,3.99,30723.0,7661870.9,2023
1,2023-01-02,243.0,260.1,240.0,260.0,5.05,30548.0,7724791.4,2023
2,2023-01-03,263.0,267.0,253.0,254.0,-2.31,18165.0,4658482.0,2023
3,2023-01-04,250.0,272.0,250.0,268.0,5.51,19898.0,5278879.5,2023
4,2023-01-05,273.3,281.0,263.0,274.9,2.57,15850.0,4303330.3,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,274.0,276.4,270.0,275.0,2.23,33131.0,9097005.7,2026
719,2026-02-25,275.0,281.8,275.0,280.0,1.82,28569.0,7993722.2,2026
720,2026-02-26,280.0,283.0,278.0,282.7,0.96,32485.0,9151407.2,2026
721,2026-03-01,278.0,286.0,277.1,284.1,0.50,37223.0,10535068.8,2026
722,2026-03-03,283.0,292.0,283.0,289.9,2.04,44798.0,12924128.5,2026

In [16]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025],      # FY end periods
    'eps': [-2.35, -4.50, -6.42, -5.80],  # NPR (Reported, negative due to losses)
    'pe-ratio': [0.00, 0.00, 0.00, 0.00],  # N/A due to negative earnings
    'roe': [-3.8, -7.2, -9.5, -8.2],       # Return on Equity (%)
    'dividend': [0.00, 0.00, 0.00, 0.00],  # No dividends due to accumulated losses
    'net-margin': [-42.0, -44.0, -54.0, -36.0], # Operating losses
    'pb-ratio': [2.8, 3.5, 4.0, 3.7],      # Market valuation relative to book value
    'debt-equity': [2.1, 2.9, 3.5, 5.1]    # High leverage prior to 2025 right share
}

df_fundamental = pd.DataFrame(fundamental_data)
print(df_fundamental)

   year   eps  pe-ratio  roe  dividend  net-margin  pb-ratio  debt-equity
0  2022 -2.35       0.0 -3.8       0.0       -42.0       2.8          2.1
1  2023 -4.50       0.0 -7.2       0.0       -44.0       3.5          2.9
2  2024 -6.42       0.0 -9.5       0.0       -54.0       4.0          3.5
3  2025 -5.80       0.0 -8.2       0.0       -36.0       3.7          5.1

In [17]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2023-01-01,238.0,260.0,238.0,247.5,3.99,30723.0,7661870.9,2023,-4.5,0.0,-7.2,0.0,-44.0,3.5,2.9
1,2023-01-02,243.0,260.1,240.0,260.0,5.05,30548.0,7724791.4,2023,-4.5,0.0,-7.2,0.0,-44.0,3.5,2.9
2,2023-01-03,263.0,267.0,253.0,254.0,-2.31,18165.0,4658482.0,2023,-4.5,0.0,-7.2,0.0,-44.0,3.5,2.9
3,2023-01-04,250.0,272.0,250.0,268.0,5.51,19898.0,5278879.5,2023,-4.5,0.0,-7.2,0.0,-44.0,3.5,2.9
4,2023-01-05,273.3,281.0,263.0,274.9,2.57,15850.0,4303330.3,2023,-4.5,0.0,-7.2,0.0,-44.0,3.5,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,274.0,276.4,270.0,275.0,2.23,33131.0,9097005.7,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,2026-02-25,275.0,281.8,275.0,280.0,1.82,28569.0,7993722.2,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,2026-02-26,280.0,283.0,278.0,282.7,0.96,32485.0,9151407.2,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,2026-03-01,278.0,286.0,277.1,284.1,0.50,37223.0,10535068.8,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,2026-03-03,283.0,292.0,283.0,289.9,2.04,44798.0,12924128.5,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/CHL.csv', index = False)