In [2]:
#importing the pandas library
import pandas as pd

In [3]:

#reading the file
df = pd.read_csv('../../data-companywise/raw_data/GBBL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,6/5/2011,132.0,134.0,128.0,128.0,NaN,810,105900.0,0
1,6/6/2011,128.0,130.0,123.0,123.0,-3.91,1990,255370.0,0
2,6/7/2011,123.0,122.0,116.0,116.0,-5.69,1980,233910.0,0
3,6/8/2011,116.0,118.0,112.0,112.0,-3.45,590,67160.0,0
4,6/9/2011,112.0,114.0,112.0,112.0,0.00,60,6800.0,0
...,...,...,...,...,...,...,...,...,...
3079,3/3/2026,406.8,415.0,402.0,408.0,0.25,34297,14060051.1,1
3080,3/9/2026,416.0,424.0,416.1,424.0,4.02,210,89041.0,1
3081,3/10/2026,432.0,442.0,420.0,425.0,0.14,85091,36300000.0,1
3082,3/11/2026,428.0,432.0,420.0,420.0,-1.18,42801,18200000.0,-1
3083,3/12/2026,413.2,424.0,413.2,421.0,0.12,28334,11900000.0,1

In [4]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,6/5/2011,132.0,134.0,128.0,128.0,NaN,810,105900.0
1,6/6/2011,128.0,130.0,123.0,123.0,-3.91,1990,255370.0
2,6/7/2011,123.0,122.0,116.0,116.0,-5.69,1980,233910.0
3,6/8/2011,116.0,118.0,112.0,112.0,-3.45,590,67160.0
4,6/9/2011,112.0,114.0,112.0,112.0,0.00,60,6800.0
...,...,...,...,...,...,...,...,...
3079,3/3/2026,406.8,415.0,402.0,408.0,0.25,34297,14060051.1
3080,3/9/2026,416.0,424.0,416.1,424.0,4.02,210,89041.0
3081,3/10/2026,432.0,442.0,420.0,425.0,0.14,85091,36300000.0
3082,3/11/2026,428.0,432.0,420.0,420.0,-1.18,42801,18200000.0
3083,3/12/2026,413.2,424.0,413.2,421.0,0.12,28334,11900000.0

In [5]:

# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [6]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2011-06-05,132.0,134.0,128.0,128.0,NaN,810,105900.0,2011
1,2011-06-06,128.0,130.0,123.0,123.0,-3.91,1990,255370.0,2011
2,2011-06-07,123.0,122.0,116.0,116.0,-5.69,1980,233910.0,2011
3,2011-06-08,116.0,118.0,112.0,112.0,-3.45,590,67160.0,2011
4,2011-06-09,112.0,114.0,112.0,112.0,0.00,60,6800.0,2011
...,...,...,...,...,...,...,...,...,...
3079,2026-03-03,406.8,415.0,402.0,408.0,0.25,34297,14060051.1,2026
3080,2026-03-09,416.0,424.0,416.1,424.0,4.02,210,89041.0,2026
3081,2026-03-10,432.0,442.0,420.0,425.0,0.14,85091,36300000.0,2026
3082,2026-03-11,428.0,432.0,420.0,420.0,-1.18,42801,18200000.0,2026
3083,2026-03-12,413.2,424.0,413.2,421.0,0.12,28334,11900000.0,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2357,2023-01-01,362.1,367.0,346.0,352.0,-0.85,45037,16049405.5,2023
2358,2023-01-02,349.9,364.0,345.0,361.0,2.56,29372,10510703.9,2023
2359,2023-01-03,358.1,366.0,351.9,354.0,-1.94,42901,15417468.2,2023
2360,2023-01-04,352.0,373.0,352.0,370.0,4.52,39269,14291105.5,2023
2361,2023-01-05,377.0,378.0,364.0,366.0,-1.08,69767,25683276.1,2023
...,...,...,...,...,...,...,...,...,...
3079,2026-03-03,406.8,415.0,402.0,408.0,0.25,34297,14060051.1,2026
3080,2026-03-09,416.0,424.0,416.1,424.0,4.02,210,89041.0,2026
3081,2026-03-10,432.0,442.0,420.0,425.0,0.14,85091,36300000.0,2026
3082,2026-03-11,428.0,432.0,420.0,420.0,-1.18,42801,18200000.0,2026
3083,2026-03-12,413.2,424.0,413.2,421.0,0.12,28334,11900000.0,2026

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,362.1,367.0,346.0,352.0,-0.85,45037,16049405.5,2023
1,2023-01-02,349.9,364.0,345.0,361.0,2.56,29372,10510703.9,2023
2,2023-01-03,358.1,366.0,351.9,354.0,-1.94,42901,15417468.2,2023
3,2023-01-04,352.0,373.0,352.0,370.0,4.52,39269,14291105.5,2023
4,2023-01-05,377.0,378.0,364.0,366.0,-1.08,69767,25683276.1,2023
...,...,...,...,...,...,...,...,...,...
722,2026-03-03,406.8,415.0,402.0,408.0,0.25,34297,14060051.1,2026
723,2026-03-09,416.0,424.0,416.1,424.0,4.02,210,89041.0,2026
724,2026-03-10,432.0,442.0,420.0,425.0,0.14,85091,36300000.0,2026
725,2026-03-11,428.0,432.0,420.0,420.0,-1.18,42801,18200000.0,2026
726,2026-03-12,413.2,424.0,413.2,421.0,0.12,28334,11900000.0,2026

In [14]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # FY 78/79 to 81/82
    'eps': [21.56, 17.02, 7.64, 21.10],   # NPR (Audited & 2025 Annualized)
    'pe-ratio': [17.50, 22.30, 48.55, 19.93], # Based on price (~420 as of Mar 2026)
    'roe': [14.10, 10.85, 4.63, 13.22],   # Return on Equity (%)
    'dividend': [14.50, 10.00, 5.00, 10.53], # Total % (Bonus + Cash)
    'net-margin': [24.12, 19.45, 10.58, 26.35], # (%)
    'pb-ratio': [2.10, 2.05, 2.38, 2.63],
    'debt-equity': [9.45, 9.80, 10.12, 10.30]} # Leverage (Total Assets/Equity proxy)

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  21.56     17.50  14.10     14.50       24.12      2.10         9.45
1  2023  17.02     22.30  10.85     10.00       19.45      2.05         9.80
2  2024   7.64     48.55   4.63      5.00       10.58      2.38        10.12
3  2025  21.10     19.93  13.22     10.53       26.35      2.63        10.30

In [15]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps_x,pe-ratio_x,roe_x,dividend_x,eps_y,pe-ratio_y,roe_y,dividend_y,net-margin,pb-ratio,debt-equity
0,2023-01-01,362.1,367.0,346.0,352.0,-0.85,45037,16049405.5,2023,16.04,23.07,10.8,10.0,17.02,22.3,10.85,10.0,19.45,2.05,9.8
1,2023-01-02,349.9,364.0,345.0,361.0,2.56,29372,10510703.9,2023,16.04,23.07,10.8,10.0,17.02,22.3,10.85,10.0,19.45,2.05,9.8
2,2023-01-03,358.1,366.0,351.9,354.0,-1.94,42901,15417468.2,2023,16.04,23.07,10.8,10.0,17.02,22.3,10.85,10.0,19.45,2.05,9.8
3,2023-01-04,352.0,373.0,352.0,370.0,4.52,39269,14291105.5,2023,16.04,23.07,10.8,10.0,17.02,22.3,10.85,10.0,19.45,2.05,9.8
4,2023-01-05,377.0,378.0,364.0,366.0,-1.08,69767,25683276.1,2023,16.04,23.07,10.8,10.0,17.02,22.3,10.85,10.0,19.45,2.05,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,2026-03-03,406.8,415.0,402.0,408.0,0.25,34297,14060051.1,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
723,2026-03-09,416.0,424.0,416.1,424.0,4.02,210,89041.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
724,2026-03-10,432.0,442.0,420.0,425.0,0.14,85091,36300000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725,2026-03-11,428.0,432.0,420.0,420.0,-1.18,42801,18200000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,2026-03-12,413.2,424.0,413.2,421.0,0.12,28334,11900000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/GBBL.csv', index = False)