In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/GBIME.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2012-09-26,248.0,249.0,244.0,247.0,NaN,7227.0,1771727.0,0
1,2012-09-30,245.0,247.0,238.0,244.0,-1.21,7236.0,1747500.0,0
2,2012-10-01,244.0,245.0,240.0,243.0,-0.41,5064.0,1229940.0,0
3,2012-10-01,244.0,245.0,240.0,243.0,0.00,5064.0,1229940.0,0
4,2012-10-02,243.0,248.0,242.0,248.0,2.06,2854.0,703587.0,0
...,...,...,...,...,...,...,...,...,...
2631,2026-02-24,225.0,225.0,221.1,224.0,1.31,67421.0,15063529.2,-1
2632,2026-02-25,224.0,225.0,222.0,224.9,0.40,44087.0,9868105.3,1
2633,2026-02-26,229.3,229.3,225.0,226.7,0.80,75123.0,16962104.4,-1
2634,2026-03-01,231.2,231.2,224.5,228.0,0.57,115599.0,26259520.0,-1
2635,2026-03-03,232.5,232.5,221.5,231.0,1.32,118156.0,27244851.3,-1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2012-09-26,248.0,249.0,244.0,247.0,NaN,7227.0,1771727.0
1,2012-09-30,245.0,247.0,238.0,244.0,-1.21,7236.0,1747500.0
2,2012-10-01,244.0,245.0,240.0,243.0,-0.41,5064.0,1229940.0
3,2012-10-01,244.0,245.0,240.0,243.0,0.00,5064.0,1229940.0
4,2012-10-02,243.0,248.0,242.0,248.0,2.06,2854.0,703587.0
...,...,...,...,...,...,...,...,...
2631,2026-02-24,225.0,225.0,221.1,224.0,1.31,67421.0,15063529.2
2632,2026-02-25,224.0,225.0,222.0,224.9,0.40,44087.0,9868105.3
2633,2026-02-26,229.3,229.3,225.0,226.7,0.80,75123.0,16962104.4
2634,2026-03-01,231.2,231.2,224.5,228.0,0.57,115599.0,26259520.0
2635,2026-03-03,232.5,232.5,221.5,231.0,1.32,118156.0,27244851.3

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2012-09-26,248.0,249.0,244.0,247.0,NaN,7227.0,1771727.0
1,2012-09-30,245.0,247.0,238.0,244.0,-1.21,7236.0,1747500.0
2,2012-10-01,244.0,245.0,240.0,243.0,-0.41,5064.0,1229940.0
3,2012-10-01,244.0,245.0,240.0,243.0,0.00,5064.0,1229940.0
4,2012-10-02,243.0,248.0,242.0,248.0,2.06,2854.0,703587.0
...,...,...,...,...,...,...,...,...
2631,2026-02-24,225.0,225.0,221.1,224.0,1.31,67421.0,15063529.2
2632,2026-02-25,224.0,225.0,222.0,224.9,0.40,44087.0,9868105.3
2633,2026-02-26,229.3,229.3,225.0,226.7,0.80,75123.0,16962104.4
2634,2026-03-01,231.2,231.2,224.5,228.0,0.57,115599.0,26259520.0
2635,2026-03-03,232.5,232.5,221.5,231.0,1.32,118156.0,27244851.3

In [6]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2012-09-26,248.0,249.0,244.0,247.0,NaN,7227.0,1771727.0,2012
1,2012-09-30,245.0,247.0,238.0,244.0,-1.21,7236.0,1747500.0,2012
2,2012-10-01,244.0,245.0,240.0,243.0,-0.41,5064.0,1229940.0,2012
3,2012-10-01,244.0,245.0,240.0,243.0,0.00,5064.0,1229940.0,2012
4,2012-10-02,243.0,248.0,242.0,248.0,2.06,2854.0,703587.0,2012
...,...,...,...,...,...,...,...,...,...
2631,2026-02-24,225.0,225.0,221.1,224.0,1.31,67421.0,15063529.2,2026
2632,2026-02-25,224.0,225.0,222.0,224.9,0.40,44087.0,9868105.3,2026
2633,2026-02-26,229.3,229.3,225.0,226.7,0.80,75123.0,16962104.4,2026
2634,2026-03-01,231.2,231.2,224.5,228.0,0.57,115599.0,26259520.0,2026
2635,2026-03-03,232.5,232.5,221.5,231.0,1.32,118156.0,27244851.3,2026

In [8]:

#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
1815,2022-01-02,304.8,304.8,298.0,300.0,0.37,51165.0,15330971.4,2022
1816,2022-01-03,306.0,306.0,300.0,300.2,0.07,81164.0,24460931.9,2022
1817,2022-01-04,302.0,326.0,300.0,326.0,8.59,193324.0,59970602.7,2022
1818,2022-01-05,326.0,331.0,317.0,320.1,-1.81,145665.0,47039324.3,2022
1819,2022-01-06,320.0,332.0,315.0,330.0,3.09,95091.0,30792775.6,2022
...,...,...,...,...,...,...,...,...,...
2631,2026-02-24,225.0,225.0,221.1,224.0,1.31,67421.0,15063529.2,2026
2632,2026-02-25,224.0,225.0,222.0,224.9,0.40,44087.0,9868105.3,2026
2633,2026-02-26,229.3,229.3,225.0,226.7,0.80,75123.0,16962104.4,2026
2634,2026-03-01,231.2,231.2,224.5,228.0,0.57,115599.0,26259520.0,2026
2635,2026-03-03,232.5,232.5,221.5,231.0,1.32,118156.0,27244851.3,2026

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,304.8,304.8,298.0,300.0,0.37,51165.0,15330971.4,2022
1,2022-01-03,306.0,306.0,300.0,300.2,0.07,81164.0,24460931.9,2022
2,2022-01-04,302.0,326.0,300.0,326.0,8.59,193324.0,59970602.7,2022
3,2022-01-05,326.0,331.0,317.0,320.1,-1.81,145665.0,47039324.3,2022
4,2022-01-06,320.0,332.0,315.0,330.0,3.09,95091.0,30792775.6,2022
...,...,...,...,...,...,...,...,...,...
816,2026-02-24,225.0,225.0,221.1,224.0,1.31,67421.0,15063529.2,2026
817,2026-02-25,224.0,225.0,222.0,224.9,0.40,44087.0,9868105.3,2026
818,2026-02-26,229.3,229.3,225.0,226.7,0.80,75123.0,16962104.4,2026
819,2026-03-01,231.2,231.2,224.5,228.0,0.57,115599.0,26259520.0,2026
820,2026-03-03,232.5,232.5,221.5,231.0,1.32,118156.0,27244851.3,2026

In [11]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # Corresponding to FY 78/79, 79/80, 80/81, 81/82
    'eps': [21.72, 16.04, 18.25, 21.10],
    'pe-ratio': [12.01, 11.21, 14.54, 15.95],
    'roe': [13.57, 11.41, 10.20, 9.62],
    'dividend': [13.60, 9.00, 5.50, 8.00]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend
0  2022  21.72     12.01  13.57      13.6
1  2023  16.04     11.21  11.41       9.0
2  2024  18.25     14.54  10.20       5.5
3  2025  21.10     15.95   9.62       8.0

In [12]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2022-01-02,304.8,304.8,298.0,300.0,0.37,51165.0,15330971.4,2022,21.72,12.01,13.57,13.6
1,2022-01-03,306.0,306.0,300.0,300.2,0.07,81164.0,24460931.9,2022,21.72,12.01,13.57,13.6
2,2022-01-04,302.0,326.0,300.0,326.0,8.59,193324.0,59970602.7,2022,21.72,12.01,13.57,13.6
3,2022-01-05,326.0,331.0,317.0,320.1,-1.81,145665.0,47039324.3,2022,21.72,12.01,13.57,13.6
4,2022-01-06,320.0,332.0,315.0,330.0,3.09,95091.0,30792775.6,2022,21.72,12.01,13.57,13.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,2026-02-24,225.0,225.0,221.1,224.0,1.31,67421.0,15063529.2,2026,NaN,NaN,NaN,NaN
817,2026-02-25,224.0,225.0,222.0,224.9,0.40,44087.0,9868105.3,2026,NaN,NaN,NaN,NaN
818,2026-02-26,229.3,229.3,225.0,226.7,0.80,75123.0,16962104.4,2026,NaN,NaN,NaN,NaN
819,2026-03-01,231.2,231.2,224.5,228.0,0.57,115599.0,26259520.0,2026,NaN,NaN,NaN,NaN
820,2026-03-03,232.5,232.5,221.5,231.0,1.32,118156.0,27244851.3,2026,NaN,NaN,NaN,NaN

In [13]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/GBIME.csv', index = False)