In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/HBL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2011-04-18,540.0,535.0,535.0,535.0,NaN,216.0,115560.0,0
1,2011-04-19,535.0,530.0,506.0,506.0,-5.42,828.0,429489.0,0
2,2011-04-20,506.0,506.0,487.0,495.0,-2.17,1911.0,946979.0,0
3,2011-04-21,495.0,500.0,490.0,490.0,-1.01,556.0,274117.0,0
4,2011-04-25,490.0,499.0,498.0,499.0,1.84,104.0,51846.0,0
...,...,...,...,...,...,...,...,...,...
3110,2026-02-24,185.5,189.0,185.5,187.6,0.86,37752.0,7076288.3,1
3111,2026-02-25,187.0,189.9,187.0,187.5,-0.05,39655.0,7441311.6,1
3112,2026-02-26,191.2,191.2,187.4,188.5,0.53,52592.0,9895341.8,-1
3113,2026-03-01,189.0,191.7,186.0,191.4,1.54,83135.0,15792846.0,1
3114,2026-03-03,195.2,197.6,188.0,196.1,2.46,96785.0,18887076.2,1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2011-04-18,540.0,535.0,535.0,535.0,NaN,216.0,115560.0
1,2011-04-19,535.0,530.0,506.0,506.0,-5.42,828.0,429489.0
2,2011-04-20,506.0,506.0,487.0,495.0,-2.17,1911.0,946979.0
3,2011-04-21,495.0,500.0,490.0,490.0,-1.01,556.0,274117.0
4,2011-04-25,490.0,499.0,498.0,499.0,1.84,104.0,51846.0
...,...,...,...,...,...,...,...,...
3110,2026-02-24,185.5,189.0,185.5,187.6,0.86,37752.0,7076288.3
3111,2026-02-25,187.0,189.9,187.0,187.5,-0.05,39655.0,7441311.6
3112,2026-02-26,191.2,191.2,187.4,188.5,0.53,52592.0,9895341.8
3113,2026-03-01,189.0,191.7,186.0,191.4,1.54,83135.0,15792846.0
3114,2026-03-03,195.2,197.6,188.0,196.1,2.46,96785.0,18887076.2

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:

df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2250,2022-06-06,390.8,390.8,358.9,358.9,-9.99,1710.0,615894.0,2022
2251,2022-06-07,351.8,351.8,323.1,323.1,-9.97,3809.0,1239026.9,2022
2252,2022-06-08,316.7,324.0,290.8,320.0,-0.96,68657.0,20908694.7,2022
2253,2022-06-09,320.0,330.0,313.6,316.0,-1.25,24390.0,7830162.7,2022
2254,2022-06-10,311.1,318.0,311.0,316.5,0.16,10122.0,3182521.5,2022
...,...,...,...,...,...,...,...,...,...
3110,2026-02-24,185.5,189.0,185.5,187.6,0.86,37752.0,7076288.3,2026
3111,2026-02-25,187.0,189.9,187.0,187.5,-0.05,39655.0,7441311.6,2026
3112,2026-02-26,191.2,191.2,187.4,188.5,0.53,52592.0,9895341.8,2026
3113,2026-03-01,189.0,191.7,186.0,191.4,1.54,83135.0,15792846.0,2026
3114,2026-03-03,195.2,197.6,188.0,196.1,2.46,96785.0,18887076.2,2026

In [8]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-06-06,390.8,390.8,358.9,358.9,-9.99,1710.0,615894.0,2022
1,2022-06-07,351.8,351.8,323.1,323.1,-9.97,3809.0,1239026.9,2022
2,2022-06-08,316.7,324.0,290.8,320.0,-0.96,68657.0,20908694.7,2022
3,2022-06-09,320.0,330.0,313.6,316.0,-1.25,24390.0,7830162.7,2022
4,2022-06-10,311.1,318.0,311.0,316.5,0.16,10122.0,3182521.5,2022
...,...,...,...,...,...,...,...,...,...
860,2026-02-24,185.5,189.0,185.5,187.6,0.86,37752.0,7076288.3,2026
861,2026-02-25,187.0,189.9,187.0,187.5,-0.05,39655.0,7441311.6,2026
862,2026-02-26,191.2,191.2,187.4,188.5,0.53,52592.0,9895341.8,2026
863,2026-03-01,189.0,191.7,186.0,191.4,1.54,83135.0,15792846.0,2026
864,2026-03-03,195.2,197.6,188.0,196.1,2.46,96785.0,18887076.2,2026

In [9]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025], 
    'eps': [18.64, 9.42, 6.75, 11.45],   
    'pe-ratio': [15.20, 22.10, 31.10, 18.89],
    'roe': [11.10, 5.80, 3.97, 6.54],   
    'dividend': [19.11, 0.00, 0.00, 0.00], 
    'net-margin': [39.54, 13.67, 7.98, 10.58],
    'pb-ratio': [1.25, 1.10, 1.22, 1.24],
    'debt-equity': [8.10, 8.23, 8.00, 7.85]}

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  18.64     15.20  11.10     19.11       39.54      1.25         8.10
1  2023   9.42     22.10   5.80      0.00       13.67      1.10         8.23
2  2024   6.75     31.10   3.97      0.00        7.98      1.22         8.00
3  2025  11.45     18.89   6.54      0.00       10.58      1.24         7.85

In [10]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-06-06,390.8,390.8,358.9,358.9,-9.99,1710.0,615894.0,2022,18.64,15.2,11.1,19.11,39.54,1.25,8.1
1,2022-06-07,351.8,351.8,323.1,323.1,-9.97,3809.0,1239026.9,2022,18.64,15.2,11.1,19.11,39.54,1.25,8.1
2,2022-06-08,316.7,324.0,290.8,320.0,-0.96,68657.0,20908694.7,2022,18.64,15.2,11.1,19.11,39.54,1.25,8.1
3,2022-06-09,320.0,330.0,313.6,316.0,-1.25,24390.0,7830162.7,2022,18.64,15.2,11.1,19.11,39.54,1.25,8.1
4,2022-06-10,311.1,318.0,311.0,316.5,0.16,10122.0,3182521.5,2022,18.64,15.2,11.1,19.11,39.54,1.25,8.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
860,2026-02-24,185.5,189.0,185.5,187.6,0.86,37752.0,7076288.3,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
861,2026-02-25,187.0,189.9,187.0,187.5,-0.05,39655.0,7441311.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
862,2026-02-26,191.2,191.2,187.4,188.5,0.53,52592.0,9895341.8,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
863,2026-03-01,189.0,191.7,186.0,191.4,1.54,83135.0,15792846.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
864,2026-03-03,195.2,197.6,188.0,196.1,2.46,96785.0,18887076.2,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/HBL.csv', index = False)