In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/ICFC.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2011-05-16,165.0,165.0,162.0,162.0,NaN,150.0,24480.0,0
1,2011-05-18,162.0,160.0,160.0,160.0,-1.23,30.0,4800.0,0
2,2011-05-19,160.0,157.0,157.0,157.0,-1.88,20.0,3140.0,0
3,2011-05-23,157.0,154.0,150.0,150.0,-4.46,306.0,46784.0,0
4,2011-05-24,150.0,147.0,147.0,147.0,-2.00,100.0,14700.0,0
...,...,...,...,...,...,...,...,...,...
3025,2026-02-24,635.0,649.0,631.0,648.0,2.76,4963.0,3166380.1,1
3026,2026-02-25,644.0,652.0,640.0,645.0,-0.46,5923.0,3832687.7,1
3027,2026-02-26,650.0,650.0,640.0,650.0,0.78,6214.0,4011406.0,0
3028,2026-03-01,638.0,660.0,633.0,654.1,0.63,12001.0,7805662.4,1
3029,2026-03-03,652.0,666.0,652.0,664.4,1.57,12682.0,8400834.9,1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2011-05-16,165.0,165.0,162.0,162.0,NaN,150.0,24480.0
1,2011-05-18,162.0,160.0,160.0,160.0,-1.23,30.0,4800.0
2,2011-05-19,160.0,157.0,157.0,157.0,-1.88,20.0,3140.0
3,2011-05-23,157.0,154.0,150.0,150.0,-4.46,306.0,46784.0
4,2011-05-24,150.0,147.0,147.0,147.0,-2.00,100.0,14700.0
...,...,...,...,...,...,...,...,...
3025,2026-02-24,635.0,649.0,631.0,648.0,2.76,4963.0,3166380.1
3026,2026-02-25,644.0,652.0,640.0,645.0,-0.46,5923.0,3832687.7
3027,2026-02-26,650.0,650.0,640.0,650.0,0.78,6214.0,4011406.0
3028,2026-03-01,638.0,660.0,633.0,654.1,0.63,12001.0,7805662.4
3029,2026-03-03,652.0,666.0,652.0,664.4,1.57,12682.0,8400834.9

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2011-05-16,165.0,165.0,162.0,162.0,NaN,150.0,24480.0,2011
1,2011-05-18,162.0,160.0,160.0,160.0,-1.23,30.0,4800.0,2011
2,2011-05-19,160.0,157.0,157.0,157.0,-1.88,20.0,3140.0,2011
3,2011-05-23,157.0,154.0,150.0,150.0,-4.46,306.0,46784.0,2011
4,2011-05-24,150.0,147.0,147.0,147.0,-2.00,100.0,14700.0,2011
...,...,...,...,...,...,...,...,...,...
3025,2026-02-24,635.0,649.0,631.0,648.0,2.76,4963.0,3166380.1,2026
3026,2026-02-25,644.0,652.0,640.0,645.0,-0.46,5923.0,3832687.7,2026
3027,2026-02-26,650.0,650.0,640.0,650.0,0.78,6214.0,4011406.0,2026
3028,2026-03-01,638.0,660.0,633.0,654.1,0.63,12001.0,7805662.4,2026
3029,2026-03-03,652.0,666.0,652.0,664.4,1.57,12682.0,8400834.9,2026

In [7]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [8]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2065,2022-01-02,585.0,593.0,580.0,589.0,0.63,35465.0,20836762.7,2022
2066,2022-01-03,599.0,607.9,587.1,595.0,1.02,65710.0,39435972.3,2022
2067,2022-01-04,595.1,609.0,585.0,607.0,2.02,61815.0,37200691.4,2022
2068,2022-01-05,619.0,629.0,601.0,605.2,-0.30,86845.0,53436314.7,2022
2069,2022-01-06,597.1,617.0,595.0,614.0,1.45,45566.0,27864070.9,2022
...,...,...,...,...,...,...,...,...,...
3025,2026-02-24,635.0,649.0,631.0,648.0,2.76,4963.0,3166380.1,2026
3026,2026-02-25,644.0,652.0,640.0,645.0,-0.46,5923.0,3832687.7,2026
3027,2026-02-26,650.0,650.0,640.0,650.0,0.78,6214.0,4011406.0,2026
3028,2026-03-01,638.0,660.0,633.0,654.1,0.63,12001.0,7805662.4,2026
3029,2026-03-03,652.0,666.0,652.0,664.4,1.57,12682.0,8400834.9,2026

In [9]:

#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,585.0,593.0,580.0,589.0,0.63,35465.0,20836762.7,2022
1,2022-01-03,599.0,607.9,587.1,595.0,1.02,65710.0,39435972.3,2022
2,2022-01-04,595.1,609.0,585.0,607.0,2.02,61815.0,37200691.4,2022
3,2022-01-05,619.0,629.0,601.0,605.2,-0.30,86845.0,53436314.7,2022
4,2022-01-06,597.1,617.0,595.0,614.0,1.45,45566.0,27864070.9,2022
...,...,...,...,...,...,...,...,...,...
960,2026-02-24,635.0,649.0,631.0,648.0,2.76,4963.0,3166380.1,2026
961,2026-02-25,644.0,652.0,640.0,645.0,-0.46,5923.0,3832687.7,2026
962,2026-02-26,650.0,650.0,640.0,650.0,0.78,6214.0,4011406.0,2026
963,2026-03-01,638.0,660.0,633.0,654.1,0.63,12001.0,7805662.4,2026
964,2026-03-03,652.0,666.0,652.0,664.4,1.57,12682.0,8400834.9,2026

In [10]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], 
    'eps': [12.91, 13.97, 10.03, 22.63], 
    'pe-ratio': [31.50, 28.10, 76.70, 26.60], 
    'roe': [9.45, 9.60, 6.41, 12.92],   
    'dividend': [10.00, 6.50, 5.26, 15.79],
    'net-margin': [13.42, 8.18, 5.02, 14.04],
    'pb-ratio': [3.15, 3.40, 4.90, 3.97],
    'debt-equity': [11.80, 10.30, 9.60, 8.20]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  12.91      31.5   9.45     10.00       13.42      3.15         11.8
1  2023  13.97      28.1   9.60      6.50        8.18      3.40         10.3
2  2024  10.03      76.7   6.41      5.26        5.02      4.90          9.6
3  2025  22.63      26.6  12.92     15.79       14.04      3.97          8.2

In [11]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-01-02,585.0,593.0,580.0,589.0,0.63,35465.0,20836762.7,2022,12.91,31.5,9.45,10.0,13.42,3.15,11.8
1,2022-01-03,599.0,607.9,587.1,595.0,1.02,65710.0,39435972.3,2022,12.91,31.5,9.45,10.0,13.42,3.15,11.8
2,2022-01-04,595.1,609.0,585.0,607.0,2.02,61815.0,37200691.4,2022,12.91,31.5,9.45,10.0,13.42,3.15,11.8
3,2022-01-05,619.0,629.0,601.0,605.2,-0.30,86845.0,53436314.7,2022,12.91,31.5,9.45,10.0,13.42,3.15,11.8
4,2022-01-06,597.1,617.0,595.0,614.0,1.45,45566.0,27864070.9,2022,12.91,31.5,9.45,10.0,13.42,3.15,11.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,2026-02-24,635.0,649.0,631.0,648.0,2.76,4963.0,3166380.1,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961,2026-02-25,644.0,652.0,640.0,645.0,-0.46,5923.0,3832687.7,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
962,2026-02-26,650.0,650.0,640.0,650.0,0.78,6214.0,4011406.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963,2026-03-01,638.0,660.0,633.0,654.1,0.63,12001.0,7805662.4,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964,2026-03-03,652.0,666.0,652.0,664.4,1.57,12682.0,8400834.9,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/ICFC.csv', index = False)