In [1]:
#importing the pandas library
import pandas as pd

In [2]:

#reading the file
df = pd.read_csv('../../data-companywise/raw_data/KSBBL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,9/26/2017,216.0,218.0,214.0,218.0,NaN,10633,2293346.0,0
1,10/3/2017,218.0,218.0,213.0,217.0,-0.46,2751,590465.0,0
2,10/4/2017,217.0,222.0,215.0,215.0,-0.92,6871,1497538.0,0
3,10/8/2017,215.0,212.0,203.0,211.0,-1.86,12008,2473364.0,0
4,10/9/2017,211.0,212.0,204.0,206.0,-2.37,7255,1502034.0,0
...,...,...,...,...,...,...,...,...,...
1929,3/3/2026,462.0,475.9,461.1,468.0,1.30,27792,13091200.9,1
1930,3/9/2026,477.3,506.4,477.3,496.0,5.98,4971,2407000.0,1
1931,3/10/2026,505.9,505.9,481.0,492.0,-0.83,119000,58300000.0,-1
1932,3/11/2026,500.0,500.0,480.5,484.0,-1.61,93239,45500000.0,-1
1933,3/12/2026,480.0,491.0,480.0,488.0,0.83,37996,18500000.0,1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,9/26/2017,216.0,218.0,214.0,218.0,NaN,10633,2293346.0
1,10/3/2017,218.0,218.0,213.0,217.0,-0.46,2751,590465.0
2,10/4/2017,217.0,222.0,215.0,215.0,-0.92,6871,1497538.0
3,10/8/2017,215.0,212.0,203.0,211.0,-1.86,12008,2473364.0
4,10/9/2017,211.0,212.0,204.0,206.0,-2.37,7255,1502034.0
...,...,...,...,...,...,...,...,...
1929,3/3/2026,462.0,475.9,461.1,468.0,1.30,27792,13091200.9
1930,3/9/2026,477.3,506.4,477.3,496.0,5.98,4971,2407000.0
1931,3/10/2026,505.9,505.9,481.0,492.0,-0.83,119000,58300000.0
1932,3/11/2026,500.0,500.0,480.5,484.0,-1.61,93239,45500000.0
1933,3/12/2026,480.0,491.0,480.0,488.0,0.83,37996,18500000.0

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
965,2022-01-02,440.0,450.8,430.1,448.0,2.99,44696,19810900.2,2022
966,2022-01-03,456.9,469.0,449.0,459.0,2.46,57667,26522386.3,2022
967,2022-01-04,467.9,491.6,452.1,489.0,6.54,102186,48641547.6,2022
968,2022-01-05,495.0,504.0,474.0,474.0,-3.07,84716,41381457.5,2022
969,2022-01-06,474.0,491.6,466.0,486.0,2.53,84786,40726679.0,2022
...,...,...,...,...,...,...,...,...,...
1929,2026-03-03,462.0,475.9,461.1,468.0,1.30,27792,13091200.9,2026
1930,2026-03-09,477.3,506.4,477.3,496.0,5.98,4971,2407000.0,2026
1931,2026-03-10,505.9,505.9,481.0,492.0,-0.83,119000,58300000.0,2026
1932,2026-03-11,500.0,500.0,480.5,484.0,-1.61,93239,45500000.0,2026
1933,2026-03-12,480.0,491.0,480.0,488.0,0.83,37996,18500000.0,2026

In [8]:

#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,440.0,450.8,430.1,448.0,2.99,44696,19810900.2,2022
1,2022-01-03,456.9,469.0,449.0,459.0,2.46,57667,26522386.3,2022
2,2022-01-04,467.9,491.6,452.1,489.0,6.54,102186,48641547.6,2022
3,2022-01-05,495.0,504.0,474.0,474.0,-3.07,84716,41381457.5,2022
4,2022-01-06,474.0,491.6,466.0,486.0,2.53,84786,40726679.0,2022
...,...,...,...,...,...,...,...,...,...
964,2026-03-03,462.0,475.9,461.1,468.0,1.30,27792,13091200.9,2026
965,2026-03-09,477.3,506.4,477.3,496.0,5.98,4971,2407000.0,2026
966,2026-03-10,505.9,505.9,481.0,492.0,-0.83,119000,58300000.0,2026
967,2026-03-11,500.0,500.0,480.5,484.0,-1.61,93239,45500000.0,2026
968,2026-03-12,480.0,491.0,480.0,488.0,0.83,37996,18500000.0,2026

In [9]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [18.38, 11.01, 16.48, 20.43],  
    'pe-ratio': [18.50, 22.10, 24.12, 22.17], 
    'roe': [11.18, 7.63, 11.10, 12.57], 
    'dividend': [0.00, 4.63, 12.00, 15.79],
    'net-margin': [11.80, 10.45, 12.10, 12.70],
    'pb-ratio': [2.65, 2.85, 3.15, 3.10],
    'debt-equity': [9.40, 9.80, 9.55, 9.20]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  18.38     18.50  11.18      0.00       11.80      2.65         9.40
1  2023  11.01     22.10   7.63      4.63       10.45      2.85         9.80
2  2024  16.48     24.12  11.10     12.00       12.10      3.15         9.55
3  2025  20.43     22.17  12.57     15.79       12.70      3.10         9.20

In [10]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-01-02,440.0,450.8,430.1,448.0,2.99,44696,19810900.2,2022,18.38,18.5,11.18,0.0,11.8,2.65,9.4
1,2022-01-03,456.9,469.0,449.0,459.0,2.46,57667,26522386.3,2022,18.38,18.5,11.18,0.0,11.8,2.65,9.4
2,2022-01-04,467.9,491.6,452.1,489.0,6.54,102186,48641547.6,2022,18.38,18.5,11.18,0.0,11.8,2.65,9.4
3,2022-01-05,495.0,504.0,474.0,474.0,-3.07,84716,41381457.5,2022,18.38,18.5,11.18,0.0,11.8,2.65,9.4
4,2022-01-06,474.0,491.6,466.0,486.0,2.53,84786,40726679.0,2022,18.38,18.5,11.18,0.0,11.8,2.65,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,2026-03-03,462.0,475.9,461.1,468.0,1.30,27792,13091200.9,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,2026-03-09,477.3,506.4,477.3,496.0,5.98,4971,2407000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,2026-03-10,505.9,505.9,481.0,492.0,-0.83,119000,58300000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
967,2026-03-11,500.0,500.0,480.5,484.0,-1.61,93239,45500000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
968,2026-03-12,480.0,491.0,480.0,488.0,0.83,37996,18500000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/KSBBL.csv', index = False)