In [1]:
#importing the pandas library
import pandas as pd

In [2]:

#reading the file
df = pd.read_csv('../data-companywise/raw_data/KSBBL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2017-09-26,216.0,218.0,214.0,218.0,NaN,10633.0,2293346.0,0
1,2017-10-03,218.0,218.0,213.0,217.0,-0.46,2751.0,590465.0,0
2,2017-10-04,217.0,222.0,215.0,215.0,-0.92,6871.0,1497538.0,0
3,2017-10-08,215.0,212.0,203.0,211.0,-1.86,12008.0,2473364.0,0
4,2017-10-09,211.0,212.0,204.0,206.0,-2.37,7255.0,1502034.0,0
...,...,...,...,...,...,...,...,...,...
1925,2026-02-24,452.0,458.0,452.0,458.0,1.33,18427.0,8393462.8,1
1926,2026-02-25,461.0,466.0,456.0,460.0,0.44,23165.0,10624798.1,-1
1927,2026-02-26,469.2,469.2,457.0,458.0,-0.43,14232.0,6543513.3,-1
1928,2026-03-01,467.1,471.2,452.3,462.0,0.87,15816.0,7355739.7,-1
1929,2026-03-03,462.0,475.9,461.1,468.0,1.30,27792.0,13091200.9,1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2017-09-26,216.0,218.0,214.0,218.0,NaN,10633.0,2293346.0
1,2017-10-03,218.0,218.0,213.0,217.0,-0.46,2751.0,590465.0
2,2017-10-04,217.0,222.0,215.0,215.0,-0.92,6871.0,1497538.0
3,2017-10-08,215.0,212.0,203.0,211.0,-1.86,12008.0,2473364.0
4,2017-10-09,211.0,212.0,204.0,206.0,-2.37,7255.0,1502034.0
...,...,...,...,...,...,...,...,...
1925,2026-02-24,452.0,458.0,452.0,458.0,1.33,18427.0,8393462.8
1926,2026-02-25,461.0,466.0,456.0,460.0,0.44,23165.0,10624798.1
1927,2026-02-26,469.2,469.2,457.0,458.0,-0.43,14232.0,6543513.3
1928,2026-03-01,467.1,471.2,452.3,462.0,0.87,15816.0,7355739.7
1929,2026-03-03,462.0,475.9,461.1,468.0,1.30,27792.0,13091200.9

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
965,2022-01-02,440.0,450.8,430.1,448.0,2.99,44696.0,19810900.2,2022
966,2022-01-03,456.9,469.0,449.0,459.0,2.46,57667.0,26522386.3,2022
967,2022-01-04,467.9,491.6,452.1,489.0,6.54,102186.0,48641547.6,2022
968,2022-01-05,495.0,504.0,474.0,474.0,-3.07,84716.0,41381457.5,2022
969,2022-01-06,474.0,491.6,466.0,486.0,2.53,84786.0,40726679.0,2022
...,...,...,...,...,...,...,...,...,...
1925,2026-02-24,452.0,458.0,452.0,458.0,1.33,18427.0,8393462.8,2026
1926,2026-02-25,461.0,466.0,456.0,460.0,0.44,23165.0,10624798.1,2026
1927,2026-02-26,469.2,469.2,457.0,458.0,-0.43,14232.0,6543513.3,2026
1928,2026-03-01,467.1,471.2,452.3,462.0,0.87,15816.0,7355739.7,2026
1929,2026-03-03,462.0,475.9,461.1,468.0,1.30,27792.0,13091200.9,2026

In [8]:

#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,440.0,450.8,430.1,448.0,2.99,44696.0,19810900.2,2022
1,2022-01-03,456.9,469.0,449.0,459.0,2.46,57667.0,26522386.3,2022
2,2022-01-04,467.9,491.6,452.1,489.0,6.54,102186.0,48641547.6,2022
3,2022-01-05,495.0,504.0,474.0,474.0,-3.07,84716.0,41381457.5,2022
4,2022-01-06,474.0,491.6,466.0,486.0,2.53,84786.0,40726679.0,2022
...,...,...,...,...,...,...,...,...,...
960,2026-02-24,452.0,458.0,452.0,458.0,1.33,18427.0,8393462.8,2026
961,2026-02-25,461.0,466.0,456.0,460.0,0.44,23165.0,10624798.1,2026
962,2026-02-26,469.2,469.2,457.0,458.0,-0.43,14232.0,6543513.3,2026
963,2026-03-01,467.1,471.2,452.3,462.0,0.87,15816.0,7355739.7,2026
964,2026-03-03,462.0,475.9,461.1,468.0,1.30,27792.0,13091200.9,2026

In [9]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [18.38, 11.01, 16.48, 20.43],  
    'pe-ratio': [18.50, 22.10, 24.12, 22.17], 
    'roe': [11.18, 7.63, 11.10, 12.57], 
    'dividend': [0.00, 4.63, 12.00, 15.79] 
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend
0  2022  18.38     18.50  11.18      0.00
1  2023  11.01     22.10   7.63      4.63
2  2024  16.48     24.12  11.10     12.00
3  2025  20.43     22.17  12.57     15.79

In [10]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2022-01-02,440.0,450.8,430.1,448.0,2.99,44696.0,19810900.2,2022,18.38,18.5,11.18,0.0
1,2022-01-03,456.9,469.0,449.0,459.0,2.46,57667.0,26522386.3,2022,18.38,18.5,11.18,0.0
2,2022-01-04,467.9,491.6,452.1,489.0,6.54,102186.0,48641547.6,2022,18.38,18.5,11.18,0.0
3,2022-01-05,495.0,504.0,474.0,474.0,-3.07,84716.0,41381457.5,2022,18.38,18.5,11.18,0.0
4,2022-01-06,474.0,491.6,466.0,486.0,2.53,84786.0,40726679.0,2022,18.38,18.5,11.18,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,2026-02-24,452.0,458.0,452.0,458.0,1.33,18427.0,8393462.8,2026,NaN,NaN,NaN,NaN
961,2026-02-25,461.0,466.0,456.0,460.0,0.44,23165.0,10624798.1,2026,NaN,NaN,NaN,NaN
962,2026-02-26,469.2,469.2,457.0,458.0,-0.43,14232.0,6543513.3,2026,NaN,NaN,NaN,NaN
963,2026-03-01,467.1,471.2,452.3,462.0,0.87,15816.0,7355739.7,2026,NaN,NaN,NaN,NaN
964,2026-03-03,462.0,475.9,461.1,468.0,1.30,27792.0,13091200.9,2026,NaN,NaN,NaN,NaN

In [11]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/KSBBL.csv', index = False)