In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/MEN.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2/7/2021,665.0,726.0,656.0,694.0,2.66,25785,17529590.0,1
1,2/8/2021,685.0,701.0,660.0,675.0,-2.74,26305,17664812.0,-1
2,2/9/2021,707.0,707.0,634.0,645.0,-4.44,31817,20460763.0,-1
3,2/10/2021,677.0,677.0,622.0,640.0,-0.78,26200,16625840.0,-1
4,2/11/2021,628.0,640.0,618.0,620.0,-3.13,15428,9651278.0,-1
...,...,...,...,...,...,...,...,...,...
1179,3/3/2026,599.9,603.8,588.1,599.0,0.34,47420,28375849.5,-1
1180,3/9/2026,610.9,648.1,610.9,648.0,8.20,3182,1970000.0,1
1181,3/10/2026,655.0,655.0,621.0,633.0,-2.33,226000,143000000.0,-1
1182,3/11/2026,635.0,640.0,615.0,621.0,-1.91,68072,42600000.0,-1
1183,3/12/2026,611.0,625.7,609.0,625.0,0.61,98750,61100000.0,1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2/7/2021,665.0,726.0,656.0,694.0,2.66,25785,17529590.0
1,2/8/2021,685.0,701.0,660.0,675.0,-2.74,26305,17664812.0
2,2/9/2021,707.0,707.0,634.0,645.0,-4.44,31817,20460763.0
3,2/10/2021,677.0,677.0,622.0,640.0,-0.78,26200,16625840.0
4,2/11/2021,628.0,640.0,618.0,620.0,-3.13,15428,9651278.0
...,...,...,...,...,...,...,...,...
1179,3/3/2026,599.9,603.8,588.1,599.0,0.34,47420,28375849.5
1180,3/9/2026,610.9,648.1,610.9,648.0,8.20,3182,1970000.0
1181,3/10/2026,655.0,655.0,621.0,633.0,-2.33,226000,143000000.0
1182,3/11/2026,635.0,640.0,615.0,621.0,-1.91,68072,42600000.0
1183,3/12/2026,611.0,625.7,609.0,625.0,0.61,98750,61100000.0

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2021-02-07,665.0,726.0,656.0,694.0,2.66,25785,17529590.0,2021
1,2021-02-08,685.0,701.0,660.0,675.0,-2.74,26305,17664812.0,2021
2,2021-02-09,707.0,707.0,634.0,645.0,-4.44,31817,20460763.0,2021
3,2021-02-10,677.0,677.0,622.0,640.0,-0.78,26200,16625840.0,2021
4,2021-02-11,628.0,640.0,618.0,620.0,-3.13,15428,9651278.0,2021
...,...,...,...,...,...,...,...,...,...
1179,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420,28375849.5,2026
1180,2026-03-09,610.9,648.1,610.9,648.0,8.20,3182,1970000.0,2026
1181,2026-03-10,655.0,655.0,621.0,633.0,-2.33,226000,143000000.0,2026
1182,2026-03-11,635.0,640.0,615.0,621.0,-1.91,68072,42600000.0,2026
1183,2026-03-12,611.0,625.7,609.0,625.0,0.61,98750,61100000.0,2026

In [7]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [8]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
215,2022-01-02,1030.0,1070.0,1020.0,1051.0,0.23,1790,1881840.0,2022
216,2022-01-03,1032.0,1086.3,1032.0,1065.0,1.33,6020,6501530.0,2022
217,2022-01-04,1043.7,1084.0,1027.0,1075.0,0.94,1190,1265925.0,2022
218,2022-01-05,1060.0,1120.0,1060.0,1064.4,-0.99,3867,4224058.2,2022
219,2022-01-06,1065.0,1149.0,1065.0,1120.0,5.22,12273,13738227.6,2022
...,...,...,...,...,...,...,...,...,...
1179,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420,28375849.5,2026
1180,2026-03-09,610.9,648.1,610.9,648.0,8.20,3182,1970000.0,2026
1181,2026-03-10,655.0,655.0,621.0,633.0,-2.33,226000,143000000.0,2026
1182,2026-03-11,635.0,640.0,615.0,621.0,-1.91,68072,42600000.0,2026
1183,2026-03-12,611.0,625.7,609.0,625.0,0.61,98750,61100000.0,2026

In [9]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,1030.0,1070.0,1020.0,1051.0,0.23,1790,1881840.0,2022
1,2022-01-03,1032.0,1086.3,1032.0,1065.0,1.33,6020,6501530.0,2022
2,2022-01-04,1043.7,1084.0,1027.0,1075.0,0.94,1190,1265925.0,2022
3,2022-01-05,1060.0,1120.0,1060.0,1064.4,-0.99,3867,4224058.2,2022
4,2022-01-06,1065.0,1149.0,1065.0,1120.0,5.22,12273,13738227.6,2022
...,...,...,...,...,...,...,...,...,...
964,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420,28375849.5,2026
965,2026-03-09,610.9,648.1,610.9,648.0,8.20,3182,1970000.0,2026
966,2026-03-10,655.0,655.0,621.0,633.0,-2.33,226000,143000000.0,2026
967,2026-03-11,635.0,640.0,615.0,621.0,-1.91,68072,42600000.0,2026
968,2026-03-12,611.0,625.7,609.0,625.0,0.61,98750,61100000.0,2026

In [10]:
#adding some fundamental signals
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], 
    'eps': [31.54, 38.21, 44.50, 54.24], 
    'pe-ratio': [18.72, 16.45, 13.27, 10.89], 
    'roe': [18.30, 21.10, 24.50, 26.80],  
    'dividend': [10.53, 15.79, 15.00, 21.05],
    'net-margin': [31.20, 32.50, 31.85, 33.40],
    'pb-ratio': [3.85, 4.10, 4.54, 4.35],
    'debt-equity': [1.35, 1.22, 1.15, 1.04]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio   roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  31.54     18.72  18.3     10.53       31.20      3.85         1.35
1  2023  38.21     16.45  21.1     15.79       32.50      4.10         1.22
2  2024  44.50     13.27  24.5     15.00       31.85      4.54         1.15
3  2025  54.24     10.89  26.8     21.05       33.40      4.35         1.04

In [11]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-01-02,1030.0,1070.0,1020.0,1051.0,0.23,1790,1881840.0,2022,31.54,18.72,18.3,10.53,31.2,3.85,1.35
1,2022-01-03,1032.0,1086.3,1032.0,1065.0,1.33,6020,6501530.0,2022,31.54,18.72,18.3,10.53,31.2,3.85,1.35
2,2022-01-04,1043.7,1084.0,1027.0,1075.0,0.94,1190,1265925.0,2022,31.54,18.72,18.3,10.53,31.2,3.85,1.35
3,2022-01-05,1060.0,1120.0,1060.0,1064.4,-0.99,3867,4224058.2,2022,31.54,18.72,18.3,10.53,31.2,3.85,1.35
4,2022-01-06,1065.0,1149.0,1065.0,1120.0,5.22,12273,13738227.6,2022,31.54,18.72,18.3,10.53,31.2,3.85,1.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420,28375849.5,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,2026-03-09,610.9,648.1,610.9,648.0,8.20,3182,1970000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,2026-03-10,655.0,655.0,621.0,633.0,-2.33,226000,143000000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
967,2026-03-11,635.0,640.0,615.0,621.0,-1.91,68072,42600000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
968,2026-03-12,611.0,625.7,609.0,625.0,0.61,98750,61100000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:

df = df.copy()
df.to_csv('../../data-companywise/processed_data/MEN.csv', index = False)