In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/MEN.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2021-02-07,665.0,726.0,656.0,694.0,2.66,25785.0,17529590.0,1
1,2021-02-08,685.0,701.0,660.0,675.0,-2.74,26305.0,17664812.0,-1
2,2021-02-09,707.0,707.0,634.0,645.0,-4.44,31817.0,20460763.0,-1
3,2021-02-10,677.0,677.0,622.0,640.0,-0.78,26200.0,16625840.0,-1
4,2021-02-11,628.0,640.0,618.0,620.0,-3.13,15428.0,9651278.0,-1
...,...,...,...,...,...,...,...,...,...
1175,2026-02-24,574.0,582.9,574.0,579.8,0.92,23004.0,13342342.7,1
1176,2026-02-25,580.0,587.0,579.2,580.1,0.05,23546.0,13686901.9,1
1177,2026-02-26,585.0,591.7,580.5,583.0,0.50,28984.0,16893254.9,-1
1178,2026-03-01,577.0,597.0,575.0,597.0,2.40,55667.0,32794568.3,1
1179,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420.0,28375849.5,-1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2021-02-07,665.0,726.0,656.0,694.0,2.66,25785.0,17529590.0
1,2021-02-08,685.0,701.0,660.0,675.0,-2.74,26305.0,17664812.0
2,2021-02-09,707.0,707.0,634.0,645.0,-4.44,31817.0,20460763.0
3,2021-02-10,677.0,677.0,622.0,640.0,-0.78,26200.0,16625840.0
4,2021-02-11,628.0,640.0,618.0,620.0,-3.13,15428.0,9651278.0
...,...,...,...,...,...,...,...,...
1175,2026-02-24,574.0,582.9,574.0,579.8,0.92,23004.0,13342342.7
1176,2026-02-25,580.0,587.0,579.2,580.1,0.05,23546.0,13686901.9
1177,2026-02-26,585.0,591.7,580.5,583.0,0.50,28984.0,16893254.9
1178,2026-03-01,577.0,597.0,575.0,597.0,2.40,55667.0,32794568.3
1179,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420.0,28375849.5

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2021-02-07,665.0,726.0,656.0,694.0,2.66,25785.0,17529590.0,2021
1,2021-02-08,685.0,701.0,660.0,675.0,-2.74,26305.0,17664812.0,2021
2,2021-02-09,707.0,707.0,634.0,645.0,-4.44,31817.0,20460763.0,2021
3,2021-02-10,677.0,677.0,622.0,640.0,-0.78,26200.0,16625840.0,2021
4,2021-02-11,628.0,640.0,618.0,620.0,-3.13,15428.0,9651278.0,2021
...,...,...,...,...,...,...,...,...,...
1175,2026-02-24,574.0,582.9,574.0,579.8,0.92,23004.0,13342342.7,2026
1176,2026-02-25,580.0,587.0,579.2,580.1,0.05,23546.0,13686901.9,2026
1177,2026-02-26,585.0,591.7,580.5,583.0,0.50,28984.0,16893254.9,2026
1178,2026-03-01,577.0,597.0,575.0,597.0,2.40,55667.0,32794568.3,2026
1179,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420.0,28375849.5,2026

In [7]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [8]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
215,2022-01-02,1030.0,1070.0,1020.0,1051.0,0.23,1790.0,1881840.0,2022
216,2022-01-03,1032.0,1086.3,1032.0,1065.0,1.33,6020.0,6501530.0,2022
217,2022-01-04,1043.7,1084.0,1027.0,1075.0,0.94,1190.0,1265925.0,2022
218,2022-01-05,1060.0,1120.0,1060.0,1064.4,-0.99,3867.0,4224058.2,2022
219,2022-01-06,1065.0,1149.0,1065.0,1120.0,5.22,12273.0,13738227.6,2022
...,...,...,...,...,...,...,...,...,...
1175,2026-02-24,574.0,582.9,574.0,579.8,0.92,23004.0,13342342.7,2026
1176,2026-02-25,580.0,587.0,579.2,580.1,0.05,23546.0,13686901.9,2026
1177,2026-02-26,585.0,591.7,580.5,583.0,0.50,28984.0,16893254.9,2026
1178,2026-03-01,577.0,597.0,575.0,597.0,2.40,55667.0,32794568.3,2026
1179,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420.0,28375849.5,2026

In [9]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,1030.0,1070.0,1020.0,1051.0,0.23,1790.0,1881840.0,2022
1,2022-01-03,1032.0,1086.3,1032.0,1065.0,1.33,6020.0,6501530.0,2022
2,2022-01-04,1043.7,1084.0,1027.0,1075.0,0.94,1190.0,1265925.0,2022
3,2022-01-05,1060.0,1120.0,1060.0,1064.4,-0.99,3867.0,4224058.2,2022
4,2022-01-06,1065.0,1149.0,1065.0,1120.0,5.22,12273.0,13738227.6,2022
...,...,...,...,...,...,...,...,...,...
960,2026-02-24,574.0,582.9,574.0,579.8,0.92,23004.0,13342342.7,2026
961,2026-02-25,580.0,587.0,579.2,580.1,0.05,23546.0,13686901.9,2026
962,2026-02-26,585.0,591.7,580.5,583.0,0.50,28984.0,16893254.9,2026
963,2026-03-01,577.0,597.0,575.0,597.0,2.40,55667.0,32794568.3,2026
964,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420.0,28375849.5,2026

In [10]:
#adding some fundamental signals
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # Nepali FY 78/79 to 81/82
    'eps': [31.54, 38.21, 44.50, 54.24],  # NPR (Actual reported figures)
    'pe-ratio': [18.72, 16.45, 13.27, 10.89], # Note the falling P/E despite price growth
    'roe': [18.30, 21.10, 24.50, 26.80],  # ROE is high due to low maintenance costs
    'dividend': [10.53, 15.79, 15.00, 21.05]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio   roe  dividend
0  2022  31.54     18.72  18.3     10.53
1  2023  38.21     16.45  21.1     15.79
2  2024  44.50     13.27  24.5     15.00
3  2025  54.24     10.89  26.8     21.05

In [11]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2022-01-02,1030.0,1070.0,1020.0,1051.0,0.23,1790.0,1881840.0,2022,31.54,18.72,18.3,10.53
1,2022-01-03,1032.0,1086.3,1032.0,1065.0,1.33,6020.0,6501530.0,2022,31.54,18.72,18.3,10.53
2,2022-01-04,1043.7,1084.0,1027.0,1075.0,0.94,1190.0,1265925.0,2022,31.54,18.72,18.3,10.53
3,2022-01-05,1060.0,1120.0,1060.0,1064.4,-0.99,3867.0,4224058.2,2022,31.54,18.72,18.3,10.53
4,2022-01-06,1065.0,1149.0,1065.0,1120.0,5.22,12273.0,13738227.6,2022,31.54,18.72,18.3,10.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,2026-02-24,574.0,582.9,574.0,579.8,0.92,23004.0,13342342.7,2026,NaN,NaN,NaN,NaN
961,2026-02-25,580.0,587.0,579.2,580.1,0.05,23546.0,13686901.9,2026,NaN,NaN,NaN,NaN
962,2026-02-26,585.0,591.7,580.5,583.0,0.50,28984.0,16893254.9,2026,NaN,NaN,NaN,NaN
963,2026-03-01,577.0,597.0,575.0,597.0,2.40,55667.0,32794568.3,2026,NaN,NaN,NaN,NaN
964,2026-03-03,599.9,603.8,588.1,599.0,0.34,47420.0,28375849.5,2026,NaN,NaN,NaN,NaN

In [12]:

df = df.copy()
df.to_csv('../data-companywise/processed_data/MEN.csv', index = False)