In [1]:

#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/NMB.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2011-03-29,228.0,233.0,225.0,232.0,NaN,1017.0,232392.0,0
1,2011-03-30,232.0,235.0,228.0,235.0,1.29,250.0,57260.0,0
2,2011-03-31,235.0,231.0,231.0,231.0,-1.70,1000.0,231000.0,0
3,2011-04-04,231.0,227.0,225.0,226.0,-2.16,190.0,42871.0,0
4,2011-04-06,226.0,225.0,225.0,225.0,-0.44,100.0,22500.0,0
...,...,...,...,...,...,...,...,...,...
3025,2026-02-24,235.0,235.0,232.4,234.8,0.77,11140.0,2599408.1,-1
3026,2026-02-25,236.0,236.0,233.1,234.5,-0.13,22338.0,5227786.5,-1
3027,2026-02-26,239.1,239.1,234.0,238.5,1.71,40152.0,9509203.6,-1
3028,2026-03-01,234.2,238.8,234.1,238.8,0.13,39746.0,9406032.3,1
3029,2026-03-03,243.5,243.5,235.4,241.9,1.30,31533.0,7592467.4,-1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2011-03-29,228.0,233.0,225.0,232.0,NaN,1017.0,232392.0
1,2011-03-30,232.0,235.0,228.0,235.0,1.29,250.0,57260.0
2,2011-03-31,235.0,231.0,231.0,231.0,-1.70,1000.0,231000.0
3,2011-04-04,231.0,227.0,225.0,226.0,-2.16,190.0,42871.0
4,2011-04-06,226.0,225.0,225.0,225.0,-0.44,100.0,22500.0
...,...,...,...,...,...,...,...,...
3025,2026-02-24,235.0,235.0,232.4,234.8,0.77,11140.0,2599408.1
3026,2026-02-25,236.0,236.0,233.1,234.5,-0.13,22338.0,5227786.5
3027,2026-02-26,239.1,239.1,234.0,238.5,1.71,40152.0,9509203.6
3028,2026-03-01,234.2,238.8,234.1,238.8,0.13,39746.0,9406032.3
3029,2026-03-03,243.5,243.5,235.4,241.9,1.30,31533.0,7592467.4

In [4]:

# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df.drop(columns = 'status', inplace = True)
df

KeyError: "['status'] not found in axis"

In [ ]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [ ]:
df

In [ ]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [ ]:
df

In [ ]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

In [ ]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # Corresponding to FY 78/79, 79/80, 80/81, 81/82
    'eps': [18.79, 13.06, 12.12, 17.87],
    'pe-ratio': [16.23, 15.50, 16.00, 13.50],
    'roe': [13.32, 8.66, 8.12, 10.41],
    'dividend': [8.25, 0.00, 0.00, 10.00]}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

In [ ]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

In [ ]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/NMB.csv', index = False)