In [24]:

#importing the pandas library
import pandas as pd

In [25]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/NMB.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2011-03-29,228.0,233.0,225.0,232.0,NaN,1017.0,232392.0,0
1,2011-03-30,232.0,235.0,228.0,235.0,1.29,250.0,57260.0,0
2,2011-03-31,235.0,231.0,231.0,231.0,-1.70,1000.0,231000.0,0
3,2011-04-04,231.0,227.0,225.0,226.0,-2.16,190.0,42871.0,0
4,2011-04-06,226.0,225.0,225.0,225.0,-0.44,100.0,22500.0,0
...,...,...,...,...,...,...,...,...,...
3025,2026-02-24,235.0,235.0,232.4,234.8,0.77,11140.0,2599408.1,-1
3026,2026-02-25,236.0,236.0,233.1,234.5,-0.13,22338.0,5227786.5,-1
3027,2026-02-26,239.1,239.1,234.0,238.5,1.71,40152.0,9509203.6,-1
3028,2026-03-01,234.2,238.8,234.1,238.8,0.13,39746.0,9406032.3,1
3029,2026-03-03,243.5,243.5,235.4,241.9,1.30,31533.0,7592467.4,-1

In [26]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2011-03-29,228.0,233.0,225.0,232.0,NaN,1017.0,232392.0
1,2011-03-30,232.0,235.0,228.0,235.0,1.29,250.0,57260.0
2,2011-03-31,235.0,231.0,231.0,231.0,-1.70,1000.0,231000.0
3,2011-04-04,231.0,227.0,225.0,226.0,-2.16,190.0,42871.0
4,2011-04-06,226.0,225.0,225.0,225.0,-0.44,100.0,22500.0
...,...,...,...,...,...,...,...,...
3025,2026-02-24,235.0,235.0,232.4,234.8,0.77,11140.0,2599408.1
3026,2026-02-25,236.0,236.0,233.1,234.5,-0.13,22338.0,5227786.5
3027,2026-02-26,239.1,239.1,234.0,238.5,1.71,40152.0,9509203.6
3028,2026-03-01,234.2,238.8,234.1,238.8,0.13,39746.0,9406032.3
3029,2026-03-03,243.5,243.5,235.4,241.9,1.30,31533.0,7592467.4

In [27]:

# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [28]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [29]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2011-03-29,228.0,233.0,225.0,232.0,NaN,1017.0,232392.0,2011
1,2011-03-30,232.0,235.0,228.0,235.0,1.29,250.0,57260.0,2011
2,2011-03-31,235.0,231.0,231.0,231.0,-1.70,1000.0,231000.0,2011
3,2011-04-04,231.0,227.0,225.0,226.0,-2.16,190.0,42871.0,2011
4,2011-04-06,226.0,225.0,225.0,225.0,-0.44,100.0,22500.0,2011
...,...,...,...,...,...,...,...,...,...
3025,2026-02-24,235.0,235.0,232.4,234.8,0.77,11140.0,2599408.1,2026
3026,2026-02-25,236.0,236.0,233.1,234.5,-0.13,22338.0,5227786.5,2026
3027,2026-02-26,239.1,239.1,234.0,238.5,1.71,40152.0,9509203.6,2026
3028,2026-03-01,234.2,238.8,234.1,238.8,0.13,39746.0,9406032.3,2026
3029,2026-03-03,243.5,243.5,235.4,241.9,1.30,31533.0,7592467.4,2026

In [30]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [31]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2307,2023-01-01,236.0,246.8,232.4,233.3,0.30,59109.0,13994955.7,2023
2308,2023-01-02,232.2,241.5,232.1,238.9,2.40,43136.0,10295323.4,2023
2309,2023-01-03,237.0,240.0,233.0,236.0,-1.21,43145.0,10203103.1,2023
2310,2023-01-04,235.0,241.2,234.2,240.0,1.69,46503.0,11043561.0,2023
2311,2023-01-05,243.0,245.0,236.5,238.1,-0.79,36274.0,8690895.6,2023
...,...,...,...,...,...,...,...,...,...
3025,2026-02-24,235.0,235.0,232.4,234.8,0.77,11140.0,2599408.1,2026
3026,2026-02-25,236.0,236.0,233.1,234.5,-0.13,22338.0,5227786.5,2026
3027,2026-02-26,239.1,239.1,234.0,238.5,1.71,40152.0,9509203.6,2026
3028,2026-03-01,234.2,238.8,234.1,238.8,0.13,39746.0,9406032.3,2026
3029,2026-03-03,243.5,243.5,235.4,241.9,1.30,31533.0,7592467.4,2026

In [32]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,236.0,246.8,232.4,233.3,0.30,59109.0,13994955.7,2023
1,2023-01-02,232.2,241.5,232.1,238.9,2.40,43136.0,10295323.4,2023
2,2023-01-03,237.0,240.0,233.0,236.0,-1.21,43145.0,10203103.1,2023
3,2023-01-04,235.0,241.2,234.2,240.0,1.69,46503.0,11043561.0,2023
4,2023-01-05,243.0,245.0,236.5,238.1,-0.79,36274.0,8690895.6,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,235.0,235.0,232.4,234.8,0.77,11140.0,2599408.1,2026
719,2026-02-25,236.0,236.0,233.1,234.5,-0.13,22338.0,5227786.5,2026
720,2026-02-26,239.1,239.1,234.0,238.5,1.71,40152.0,9509203.6,2026
721,2026-03-01,234.2,238.8,234.1,238.8,0.13,39746.0,9406032.3,2026
722,2026-03-03,243.5,243.5,235.4,241.9,1.30,31533.0,7592467.4,2026

In [33]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # FY 78/79, 79/80, 80/81, 81/82
    'eps': [17.02, 12.12, 10.45, 11.20],   # Adjusted for capital base
    'pe-ratio': [15.10, 18.20, 21.45, 19.80], 
    'roe': [11.65, 8.12, 6.45, 7.50],    # Showing slight recovery in 2025
    'dividend': [8.25, 0.00, 0.00, 10.00], # Corrected: 10% declared in 2025
    'net-margin': [14.15, 9.05, 8.20, 9.50], 
    'pb-ratio': [1.38, 1.25, 1.20, 1.28],   
    'debt-equity': [8.10, 8.45, 8.70, 8.85]} 

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  17.02     15.10  11.65      8.25       14.15      1.38         8.10
1  2023  12.12     18.20   8.12      0.00        9.05      1.25         8.45
2  2024  10.45     21.45   6.45      0.00        8.20      1.20         8.70
3  2025  11.20     19.80   7.50     10.00        9.50      1.28         8.85

In [34]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2023-01-01,236.0,246.8,232.4,233.3,0.30,59109.0,13994955.7,2023,12.12,18.2,8.12,0.0,9.05,1.25,8.45
1,2023-01-02,232.2,241.5,232.1,238.9,2.40,43136.0,10295323.4,2023,12.12,18.2,8.12,0.0,9.05,1.25,8.45
2,2023-01-03,237.0,240.0,233.0,236.0,-1.21,43145.0,10203103.1,2023,12.12,18.2,8.12,0.0,9.05,1.25,8.45
3,2023-01-04,235.0,241.2,234.2,240.0,1.69,46503.0,11043561.0,2023,12.12,18.2,8.12,0.0,9.05,1.25,8.45
4,2023-01-05,243.0,245.0,236.5,238.1,-0.79,36274.0,8690895.6,2023,12.12,18.2,8.12,0.0,9.05,1.25,8.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,235.0,235.0,232.4,234.8,0.77,11140.0,2599408.1,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,2026-02-25,236.0,236.0,233.1,234.5,-0.13,22338.0,5227786.5,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,2026-02-26,239.1,239.1,234.0,238.5,1.71,40152.0,9509203.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,2026-03-01,234.2,238.8,234.1,238.8,0.13,39746.0,9406032.3,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,2026-03-03,243.5,243.5,235.4,241.9,1.30,31533.0,7592467.4,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/NMB.csv', index = False)