In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/PRVU.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2015-02-15,311.0,315.0,310.0,315.0,NaN,44909.0,14076560.0,0
1,2015-02-16,315.0,323.0,310.0,323.0,2.54,88333.0,27933052.0,0
2,2015-02-16,315.0,323.0,310.0,323.0,0.00,88333.0,27933052.0,0
3,2015-02-18,323.0,335.0,321.0,335.0,3.72,134332.0,43771556.0,0
4,2015-02-22,335.0,343.0,327.0,330.0,-1.49,94575.0,31618408.0,0
...,...,...,...,...,...,...,...,...,...
2225,2026-02-24,183.0,183.0,180.5,181.5,0.00,105219.0,19076774.5,-1
2226,2026-02-25,181.6,183.0,181.1,182.4,0.50,190094.0,34608881.0,1
2227,2026-02-26,186.0,186.0,182.1,183.5,0.60,100712.0,18434286.7,-1
2228,2026-03-01,187.1,187.1,180.7,186.8,1.80,170444.0,31440566.0,-1
2229,2026-03-03,190.5,195.0,184.0,194.0,3.85,390743.0,74610874.9,1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2015-02-15,311.0,315.0,310.0,315.0,NaN,44909.0,14076560.0
1,2015-02-16,315.0,323.0,310.0,323.0,2.54,88333.0,27933052.0
2,2015-02-16,315.0,323.0,310.0,323.0,0.00,88333.0,27933052.0
3,2015-02-18,323.0,335.0,321.0,335.0,3.72,134332.0,43771556.0
4,2015-02-22,335.0,343.0,327.0,330.0,-1.49,94575.0,31618408.0
...,...,...,...,...,...,...,...,...
2225,2026-02-24,183.0,183.0,180.5,181.5,0.00,105219.0,19076774.5
2226,2026-02-25,181.6,183.0,181.1,182.4,0.50,190094.0,34608881.0
2227,2026-02-26,186.0,186.0,182.1,183.5,0.60,100712.0,18434286.7
2228,2026-03-01,187.1,187.1,180.7,186.8,1.80,170444.0,31440566.0
2229,2026-03-03,190.5,195.0,184.0,194.0,3.85,390743.0,74610874.9

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
#filtering the data from 2022 to latest
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
1507,2023-01-01,200.0,201.8,195.1,196.1,-0.91,60647.0,12016009.0,2023
1508,2023-01-02,198.0,198.0,194.0,197.4,0.66,39098.0,7672751.6,2023
1509,2023-01-03,198.0,199.9,195.0,195.9,-0.76,53549.0,10519982.1,2023
1510,2023-01-04,197.0,200.0,194.3,199.5,1.84,71643.0,14099136.7,2023
1511,2023-01-05,199.5,204.0,198.0,198.9,-0.30,114292.0,22933012.1,2023
...,...,...,...,...,...,...,...,...,...
2225,2026-02-24,183.0,183.0,180.5,181.5,0.00,105219.0,19076774.5,2026
2226,2026-02-25,181.6,183.0,181.1,182.4,0.50,190094.0,34608881.0,2026
2227,2026-02-26,186.0,186.0,182.1,183.5,0.60,100712.0,18434286.7,2026
2228,2026-03-01,187.1,187.1,180.7,186.8,1.80,170444.0,31440566.0,2026
2229,2026-03-03,190.5,195.0,184.0,194.0,3.85,390743.0,74610874.9,2026

In [8]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,200.0,201.8,195.1,196.1,-0.91,60647.0,12016009.0,2023
1,2023-01-02,198.0,198.0,194.0,197.4,0.66,39098.0,7672751.6,2023
2,2023-01-03,198.0,199.9,195.0,195.9,-0.76,53549.0,10519982.1,2023
3,2023-01-04,197.0,200.0,194.3,199.5,1.84,71643.0,14099136.7,2023
4,2023-01-05,199.5,204.0,198.0,198.9,-0.30,114292.0,22933012.1,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,183.0,183.0,180.5,181.5,0.00,105219.0,19076774.5,2026
719,2026-02-25,181.6,183.0,181.1,182.4,0.50,190094.0,34608881.0,2026
720,2026-02-26,186.0,186.0,182.1,183.5,0.60,100712.0,18434286.7,2026
721,2026-03-01,187.1,187.1,180.7,186.8,1.80,170444.0,31440566.0,2026
722,2026-03-03,190.5,195.0,184.0,194.0,3.85,390743.0,74610874.9,2026

In [9]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # FY 78/79, 79/80, 80/81, 81/82
    'eps': [17.85, 4.41, 2.17, 11.35],    # NPR (Reflects post-merger dilution and recovery)
    'pe-ratio': [12.50, 28.50, 45.10, 18.20], # Market adjusted
    'roe': [11.20, 3.10, 1.45, 7.85],      # Reflects integration-driven volatility
    'dividend': [8.00, 0.00, 0.00, 0.00],  # No dividends declared during integration/retention
    'net-margin': [18.20, 8.40, 5.20, 10.12], # (%)
    'pb-ratio': [0.95, 0.85, 0.75, 0.82],     # Trading below book value
    'debt-equity': [9.50, 10.20, 10.85, 10.15] # Leverage
}

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  17.85      12.5  11.20       8.0       18.20      0.95         9.50
1  2023   4.41      28.5   3.10       0.0        8.40      0.85        10.20
2  2024   2.17      45.1   1.45       0.0        5.20      0.75        10.85
3  2025  11.35      18.2   7.85       0.0       10.12      0.82        10.15

In [10]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2023-01-01,200.0,201.8,195.1,196.1,-0.91,60647.0,12016009.0,2023,4.41,28.5,3.1,0.0,8.4,0.85,10.2
1,2023-01-02,198.0,198.0,194.0,197.4,0.66,39098.0,7672751.6,2023,4.41,28.5,3.1,0.0,8.4,0.85,10.2
2,2023-01-03,198.0,199.9,195.0,195.9,-0.76,53549.0,10519982.1,2023,4.41,28.5,3.1,0.0,8.4,0.85,10.2
3,2023-01-04,197.0,200.0,194.3,199.5,1.84,71643.0,14099136.7,2023,4.41,28.5,3.1,0.0,8.4,0.85,10.2
4,2023-01-05,199.5,204.0,198.0,198.9,-0.30,114292.0,22933012.1,2023,4.41,28.5,3.1,0.0,8.4,0.85,10.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,183.0,183.0,180.5,181.5,0.00,105219.0,19076774.5,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,2026-02-25,181.6,183.0,181.1,182.4,0.50,190094.0,34608881.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,2026-02-26,186.0,186.0,182.1,183.5,0.60,100712.0,18434286.7,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,2026-03-01,187.1,187.1,180.7,186.8,1.80,170444.0,31440566.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,2026-03-03,190.5,195.0,184.0,194.0,3.85,390743.0,74610874.9,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/PRVU.csv', index = False)