In [1]:
#importing pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/RADHI.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2018-05-09,210.0,214.0,205.0,209.0,0.00,4020.0,834310.0,0
1,2018-05-10,208.0,210.0,207.0,207.0,-0.96,2990.0,621320.0,-1
2,2018-05-14,211.0,217.0,207.0,208.0,0.48,3780.0,801690.0,1
3,2018-05-15,205.0,222.0,205.0,213.0,2.40,5948.0,1298476.0,1
4,2018-05-16,215.0,224.0,215.0,221.0,3.76,3720.0,818880.0,1
...,...,...,...,...,...,...,...,...,...
1775,2026-02-24,831.0,859.0,831.0,855.6,0.91,188890.0,161224193.8,1
1776,2026-02-25,851.1,863.9,850.0,850.0,-0.65,112176.0,95900758.3,-1
1777,2026-02-26,852.0,853.0,846.2,849.0,-0.12,127962.0,108720021.6,-1
1778,2026-03-01,840.0,857.0,838.3,856.9,0.93,424938.0,360503140.5,1
1779,2026-03-03,874.0,880.0,846.2,873.5,1.94,239141.0,207806346.6,-1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2018-05-09,210.0,214.0,205.0,209.0,0.00,4020.0,834310.0
1,2018-05-10,208.0,210.0,207.0,207.0,-0.96,2990.0,621320.0
2,2018-05-14,211.0,217.0,207.0,208.0,0.48,3780.0,801690.0
3,2018-05-15,205.0,222.0,205.0,213.0,2.40,5948.0,1298476.0
4,2018-05-16,215.0,224.0,215.0,221.0,3.76,3720.0,818880.0
...,...,...,...,...,...,...,...,...
1775,2026-02-24,831.0,859.0,831.0,855.6,0.91,188890.0,161224193.8
1776,2026-02-25,851.1,863.9,850.0,850.0,-0.65,112176.0,95900758.3
1777,2026-02-26,852.0,853.0,846.2,849.0,-0.12,127962.0,108720021.6
1778,2026-03-01,840.0,857.0,838.3,856.9,0.93,424938.0,360503140.5
1779,2026-03-03,874.0,880.0,846.2,873.5,1.94,239141.0,207806346.6

In [4]:

# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2018-05-09,210.0,214.0,205.0,209.0,0.00,4020.0,834310.0
1,2018-05-10,208.0,210.0,207.0,207.0,-0.96,2990.0,621320.0
2,2018-05-14,211.0,217.0,207.0,208.0,0.48,3780.0,801690.0
3,2018-05-15,205.0,222.0,205.0,213.0,2.40,5948.0,1298476.0
4,2018-05-16,215.0,224.0,215.0,221.0,3.76,3720.0,818880.0
...,...,...,...,...,...,...,...,...
1775,2026-02-24,831.0,859.0,831.0,855.6,0.91,188890.0,161224193.8
1776,2026-02-25,851.1,863.9,850.0,850.0,-0.65,112176.0,95900758.3
1777,2026-02-26,852.0,853.0,846.2,849.0,-0.12,127962.0,108720021.6
1778,2026-03-01,840.0,857.0,838.3,856.9,0.93,424938.0,360503140.5
1779,2026-03-03,874.0,880.0,846.2,873.5,1.94,239141.0,207806346.6

In [6]:

df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [8]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
815,2022-01-02,556.9,558.0,545.0,553.0,1.28,12496.0,6893260.5,2022
816,2022-01-03,559.9,563.8,545.0,554.9,0.34,21227.0,11763333.5,2022
817,2022-01-04,560.0,572.0,545.0,567.0,2.18,31270.0,17609817.1,2022
818,2022-01-05,572.0,591.3,566.1,573.0,1.06,44974.0,26061520.6,2022
819,2022-01-06,573.0,591.5,562.0,587.0,2.44,25445.0,14787229.4,2022
...,...,...,...,...,...,...,...,...,...
1775,2026-02-24,831.0,859.0,831.0,855.6,0.91,188890.0,161224193.8,2026
1776,2026-02-25,851.1,863.9,850.0,850.0,-0.65,112176.0,95900758.3,2026
1777,2026-02-26,852.0,853.0,846.2,849.0,-0.12,127962.0,108720021.6,2026
1778,2026-03-01,840.0,857.0,838.3,856.9,0.93,424938.0,360503140.5,2026
1779,2026-03-03,874.0,880.0,846.2,873.5,1.94,239141.0,207806346.6,2026

In [9]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,556.9,558.0,545.0,553.0,1.28,12496.0,6893260.5,2022
1,2022-01-03,559.9,563.8,545.0,554.9,0.34,21227.0,11763333.5,2022
2,2022-01-04,560.0,572.0,545.0,567.0,2.18,31270.0,17609817.1,2022
3,2022-01-05,572.0,591.3,566.1,573.0,1.06,44974.0,26061520.6,2022
4,2022-01-06,573.0,591.5,562.0,587.0,2.44,25445.0,14787229.4,2022
...,...,...,...,...,...,...,...,...,...
960,2026-02-24,831.0,859.0,831.0,855.6,0.91,188890.0,161224193.8,2026
961,2026-02-25,851.1,863.9,850.0,850.0,-0.65,112176.0,95900758.3,2026
962,2026-02-26,852.0,853.0,846.2,849.0,-0.12,127962.0,108720021.6,2026
963,2026-03-01,840.0,857.0,838.3,856.9,0.93,424938.0,360503140.5,2026
964,2026-03-03,874.0,880.0,846.2,873.5,1.94,239141.0,207806346.6,2026

In [10]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [9.93, 7.22, 20.65, 60.58],  
    'pe-ratio': [45.2, 58.1, 37.4, 13.9], 
    'roe': [8.70, 6.30, 17.10, 26.57],   
    'dividend': [5.00, 5.00, 5.00, 5.00],
    'net-margin': [33.56, 32.92, 60.94, 63.84],
    'pb-ratio': [3.10, 3.40, 5.70, 5.50],
    'debt-equity': [1.12, 0.98, 0.65, 0.42]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022   9.93      45.2   8.70       5.0       33.56       3.1         1.12
1  2023   7.22      58.1   6.30       5.0       32.92       3.4         0.98
2  2024  20.65      37.4  17.10       5.0       60.94       5.7         0.65
3  2025  60.58      13.9  26.57       5.0       63.84       5.5         0.42

In [11]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-01-02,556.9,558.0,545.0,553.0,1.28,12496.0,6893260.5,2022,9.93,45.2,8.7,5.0,33.56,3.1,1.12
1,2022-01-03,559.9,563.8,545.0,554.9,0.34,21227.0,11763333.5,2022,9.93,45.2,8.7,5.0,33.56,3.1,1.12
2,2022-01-04,560.0,572.0,545.0,567.0,2.18,31270.0,17609817.1,2022,9.93,45.2,8.7,5.0,33.56,3.1,1.12
3,2022-01-05,572.0,591.3,566.1,573.0,1.06,44974.0,26061520.6,2022,9.93,45.2,8.7,5.0,33.56,3.1,1.12
4,2022-01-06,573.0,591.5,562.0,587.0,2.44,25445.0,14787229.4,2022,9.93,45.2,8.7,5.0,33.56,3.1,1.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,2026-02-24,831.0,859.0,831.0,855.6,0.91,188890.0,161224193.8,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961,2026-02-25,851.1,863.9,850.0,850.0,-0.65,112176.0,95900758.3,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
962,2026-02-26,852.0,853.0,846.2,849.0,-0.12,127962.0,108720021.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963,2026-03-01,840.0,857.0,838.3,856.9,0.93,424938.0,360503140.5,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964,2026-03-03,874.0,880.0,846.2,873.5,1.94,239141.0,207806346.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/RADHI.csv', index = False)