In [14]:
#importing the pandas library
import pandas as pd

In [15]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/RURU.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2021-07-05,898.0,910.0,895.0,905.0,-0.88,1966.0,1773093.0,-1
1,2021-07-06,905.0,945.0,892.0,910.0,0.55,1340.0,1227810.0,1
2,2021-07-07,893.0,907.0,893.0,907.0,-0.33,600.0,540534.0,-1
3,2021-07-08,907.0,925.0,896.0,902.0,-0.55,2672.0,2432264.0,-1
4,2021-07-11,901.0,930.0,900.0,909.0,0.78,2120.0,1933450.0,1
...,...,...,...,...,...,...,...,...,...
1075,2026-02-24,649.0,656.0,645.2,653.0,0.62,2926.0,1901820.3,1
1076,2026-02-25,663.0,663.0,650.0,654.9,0.29,3547.0,2314346.1,-1
1077,2026-02-26,651.0,660.0,650.0,657.6,0.41,2711.0,1777566.2,1
1078,2026-03-01,645.1,665.0,644.5,660.0,0.36,6572.0,4326310.2,1
1079,2026-03-03,669.8,673.0,656.2,668.9,1.35,5521.0,3678401.6,-1

In [16]:
#dropping the status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2021-07-05,898.0,910.0,895.0,905.0,-0.88,1966.0,1773093.0
1,2021-07-06,905.0,945.0,892.0,910.0,0.55,1340.0,1227810.0
2,2021-07-07,893.0,907.0,893.0,907.0,-0.33,600.0,540534.0
3,2021-07-08,907.0,925.0,896.0,902.0,-0.55,2672.0,2432264.0
4,2021-07-11,901.0,930.0,900.0,909.0,0.78,2120.0,1933450.0
...,...,...,...,...,...,...,...,...
1075,2026-02-24,649.0,656.0,645.2,653.0,0.62,2926.0,1901820.3
1076,2026-02-25,663.0,663.0,650.0,654.9,0.29,3547.0,2314346.1
1077,2026-02-26,651.0,660.0,650.0,657.6,0.41,2711.0,1777566.2
1078,2026-03-01,645.1,665.0,644.5,660.0,0.36,6572.0,4326310.2
1079,2026-03-03,669.8,673.0,656.2,668.9,1.35,5521.0,3678401.6

In [17]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [18]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2021-07-05,898.0,910.0,895.0,905.0,-0.88,1966.0,1773093.0
1,2021-07-06,905.0,945.0,892.0,910.0,0.55,1340.0,1227810.0
2,2021-07-07,893.0,907.0,893.0,907.0,-0.33,600.0,540534.0
3,2021-07-08,907.0,925.0,896.0,902.0,-0.55,2672.0,2432264.0
4,2021-07-11,901.0,930.0,900.0,909.0,0.78,2120.0,1933450.0
...,...,...,...,...,...,...,...,...
1075,2026-02-24,649.0,656.0,645.2,653.0,0.62,2926.0,1901820.3
1076,2026-02-25,663.0,663.0,650.0,654.9,0.29,3547.0,2314346.1
1077,2026-02-26,651.0,660.0,650.0,657.6,0.41,2711.0,1777566.2
1078,2026-03-01,645.1,665.0,644.5,660.0,0.36,6572.0,4326310.2
1079,2026-03-03,669.8,673.0,656.2,668.9,1.35,5521.0,3678401.6

In [19]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [20]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2021-07-05,898.0,910.0,895.0,905.0,-0.88,1966.0,1773093.0,2021
1,2021-07-06,905.0,945.0,892.0,910.0,0.55,1340.0,1227810.0,2021
2,2021-07-07,893.0,907.0,893.0,907.0,-0.33,600.0,540534.0,2021
3,2021-07-08,907.0,925.0,896.0,902.0,-0.55,2672.0,2432264.0,2021
4,2021-07-11,901.0,930.0,900.0,909.0,0.78,2120.0,1933450.0,2021
...,...,...,...,...,...,...,...,...,...
1075,2026-02-24,649.0,656.0,645.2,653.0,0.62,2926.0,1901820.3,2026
1076,2026-02-25,663.0,663.0,650.0,654.9,0.29,3547.0,2314346.1,2026
1077,2026-02-26,651.0,660.0,650.0,657.6,0.41,2711.0,1777566.2,2026
1078,2026-03-01,645.1,665.0,644.5,660.0,0.36,6572.0,4326310.2,2026
1079,2026-03-03,669.8,673.0,656.2,668.9,1.35,5521.0,3678401.6,2026

In [21]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [22]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
357,2023-01-01,755.0,769.9,755.0,756.1,1.49,2639.0,2021294.6,2023
358,2023-01-02,748.1,769.0,748.1,767.0,1.44,691.0,527453.0,2023
359,2023-01-03,767.0,780.0,758.0,758.0,-1.17,797.0,616613.5,2023
360,2023-01-04,765.0,806.9,765.0,806.9,6.45,2569.0,2042077.8,2023
361,2023-01-05,822.0,831.4,800.1,815.0,1.00,3177.0,2590288.1,2023
...,...,...,...,...,...,...,...,...,...
1075,2026-02-24,649.0,656.0,645.2,653.0,0.62,2926.0,1901820.3,2026
1076,2026-02-25,663.0,663.0,650.0,654.9,0.29,3547.0,2314346.1,2026
1077,2026-02-26,651.0,660.0,650.0,657.6,0.41,2711.0,1777566.2,2026
1078,2026-03-01,645.1,665.0,644.5,660.0,0.36,6572.0,4326310.2,2026
1079,2026-03-03,669.8,673.0,656.2,668.9,1.35,5521.0,3678401.6,2026

In [23]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,755.0,769.9,755.0,756.1,1.49,2639.0,2021294.6,2023
1,2023-01-02,748.1,769.0,748.1,767.0,1.44,691.0,527453.0,2023
2,2023-01-03,767.0,780.0,758.0,758.0,-1.17,797.0,616613.5,2023
3,2023-01-04,765.0,806.9,765.0,806.9,6.45,2569.0,2042077.8,2023
4,2023-01-05,822.0,831.4,800.1,815.0,1.00,3177.0,2590288.1,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,649.0,656.0,645.2,653.0,0.62,2926.0,1901820.3,2026
719,2026-02-25,663.0,663.0,650.0,654.9,0.29,3547.0,2314346.1,2026
720,2026-02-26,651.0,660.0,650.0,657.6,0.41,2711.0,1777566.2,2026
721,2026-03-01,645.1,665.0,644.5,660.0,0.36,6572.0,4326310.2,2026
722,2026-03-03,669.8,673.0,656.2,668.9,1.35,5521.0,3678401.6,2026

In [24]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [15.22, 17.14, 14.62, 18.59],
    'pe-ratio': [58.40, 48.20, 50.80, 35.34],
    'roe': [12.30, 14.45, 11.39, 13.97],
    'dividend': [10.53, 10.53, 15.79, 15.79]}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend
0  2022  15.22     58.40  12.30     10.53
1  2023  17.14     48.20  14.45     10.53
2  2024  14.62     50.80  11.39     15.79
3  2025  18.59     35.34  13.97     15.79

In [25]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2023-01-01,755.0,769.9,755.0,756.1,1.49,2639.0,2021294.6,2023,17.14,48.2,14.45,10.53
1,2023-01-02,748.1,769.0,748.1,767.0,1.44,691.0,527453.0,2023,17.14,48.2,14.45,10.53
2,2023-01-03,767.0,780.0,758.0,758.0,-1.17,797.0,616613.5,2023,17.14,48.2,14.45,10.53
3,2023-01-04,765.0,806.9,765.0,806.9,6.45,2569.0,2042077.8,2023,17.14,48.2,14.45,10.53
4,2023-01-05,822.0,831.4,800.1,815.0,1.00,3177.0,2590288.1,2023,17.14,48.2,14.45,10.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,649.0,656.0,645.2,653.0,0.62,2926.0,1901820.3,2026,NaN,NaN,NaN,NaN
719,2026-02-25,663.0,663.0,650.0,654.9,0.29,3547.0,2314346.1,2026,NaN,NaN,NaN,NaN
720,2026-02-26,651.0,660.0,650.0,657.6,0.41,2711.0,1777566.2,2026,NaN,NaN,NaN,NaN
721,2026-03-01,645.1,665.0,644.5,660.0,0.36,6572.0,4326310.2,2026,NaN,NaN,NaN,NaN
722,2026-03-03,669.8,673.0,656.2,668.9,1.35,5521.0,3678401.6,2026,NaN,NaN,NaN,NaN

In [26]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/RURU.csv', index = False)