In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/SANIMA.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2012-04-12,146.0,160.0,148.0,160.0,NaN,12740.0,1943915.0,0
1,2012-04-15,160.0,176.0,163.0,176.0,10.00,6574.0,1152504.0,0
2,2012-04-16,176.0,191.0,179.0,191.0,8.52,8164.0,1548134.0,0
3,2012-04-17,191.0,210.0,181.0,181.0,-5.24,9132.0,1785804.0,0
4,2012-04-18,181.0,195.0,165.0,190.0,4.97,19469.0,3558240.0,0
...,...,...,...,...,...,...,...,...,...
3175,2026-02-24,332.0,338.0,327.0,333.1,0.48,37561.0,12502148.0,1
3176,2026-02-25,333.0,337.0,331.1,335.0,0.57,24261.0,8113726.7,1
3177,2026-02-26,341.7,341.7,332.1,333.0,-0.60,34106.0,11393860.2,-1
3178,2026-03-01,333.0,338.7,328.0,335.0,0.60,71245.0,23864542.7,1
3179,2026-03-03,340.0,341.0,335.0,341.0,1.79,53698.0,18182155.0,1

In [3]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [4]:
df.drop(columns = 'status', inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2012-04-12,146.0,160.0,148.0,160.0,NaN,12740.0,1943915.0
1,2012-04-15,160.0,176.0,163.0,176.0,10.00,6574.0,1152504.0
2,2012-04-16,176.0,191.0,179.0,191.0,8.52,8164.0,1548134.0
3,2012-04-17,191.0,210.0,181.0,181.0,-5.24,9132.0,1785804.0
4,2012-04-18,181.0,195.0,165.0,190.0,4.97,19469.0,3558240.0
...,...,...,...,...,...,...,...,...
3175,2026-02-24,332.0,338.0,327.0,333.1,0.48,37561.0,12502148.0
3176,2026-02-25,333.0,337.0,331.1,335.0,0.57,24261.0,8113726.7
3177,2026-02-26,341.7,341.7,332.1,333.0,-0.60,34106.0,11393860.2
3178,2026-03-01,333.0,338.7,328.0,335.0,0.60,71245.0,23864542.7
3179,2026-03-03,340.0,341.0,335.0,341.0,1.79,53698.0,18182155.0

In [5]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
#filtering the data from 2022 to 2025
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2457,2023-01-01,240.0,244.0,238.0,239.0,-0.42,35790.0,8587576.4,2023
2458,2023-01-02,240.0,243.0,236.0,240.0,0.42,26429.0,6347179.0,2023
2459,2023-01-03,241.0,241.0,237.0,237.5,-1.04,37602.0,8977639.6,2023
2460,2023-01-04,239.0,242.7,235.2,242.5,2.11,29700.0,7094300.4,2023
2461,2023-01-05,242.0,246.8,238.0,246.8,1.77,59299.0,14317855.9,2023
...,...,...,...,...,...,...,...,...,...
3175,2026-02-24,332.0,338.0,327.0,333.1,0.48,37561.0,12502148.0,2026
3176,2026-02-25,333.0,337.0,331.1,335.0,0.57,24261.0,8113726.7,2026
3177,2026-02-26,341.7,341.7,332.1,333.0,-0.60,34106.0,11393860.2,2026
3178,2026-03-01,333.0,338.7,328.0,335.0,0.60,71245.0,23864542.7,2026
3179,2026-03-03,340.0,341.0,335.0,341.0,1.79,53698.0,18182155.0,2026

In [8]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,240.0,244.0,238.0,239.0,-0.42,35790.0,8587576.4,2023
1,2023-01-02,240.0,243.0,236.0,240.0,0.42,26429.0,6347179.0,2023
2,2023-01-03,241.0,241.0,237.0,237.5,-1.04,37602.0,8977639.6,2023
3,2023-01-04,239.0,242.7,235.2,242.5,2.11,29700.0,7094300.4,2023
4,2023-01-05,242.0,246.8,238.0,246.8,1.77,59299.0,14317855.9,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,332.0,338.0,327.0,333.1,0.48,37561.0,12502148.0,2026
719,2026-02-25,333.0,337.0,331.1,335.0,0.57,24261.0,8113726.7,2026
720,2026-02-26,341.7,341.7,332.1,333.0,-0.60,34106.0,11393860.2,2026
721,2026-03-01,333.0,338.7,328.0,335.0,0.60,71245.0,23864542.7,2026
722,2026-03-03,340.0,341.0,335.0,341.0,1.79,53698.0,18182155.0,2026

In [9]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # Corresponding to FY 78/79, 79/80, 80/81, 81/82
    'eps': [18.47, 21.02, 13.40, 20.48],
    'pe-ratio': [14.10, 12.39, 24.80, 16.27],
    'roe': [11.85, 13.50, 8.40, 12.24],
    'dividend': [10.98, 14.70, 5.26, 7.37]}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend
0  2022  18.47     14.10  11.85     10.98
1  2023  21.02     12.39  13.50     14.70
2  2024  13.40     24.80   8.40      5.26
3  2025  20.48     16.27  12.24      7.37

In [10]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2023-01-01,240.0,244.0,238.0,239.0,-0.42,35790.0,8587576.4,2023,21.02,12.39,13.5,14.7
1,2023-01-02,240.0,243.0,236.0,240.0,0.42,26429.0,6347179.0,2023,21.02,12.39,13.5,14.7
2,2023-01-03,241.0,241.0,237.0,237.5,-1.04,37602.0,8977639.6,2023,21.02,12.39,13.5,14.7
3,2023-01-04,239.0,242.7,235.2,242.5,2.11,29700.0,7094300.4,2023,21.02,12.39,13.5,14.7
4,2023-01-05,242.0,246.8,238.0,246.8,1.77,59299.0,14317855.9,2023,21.02,12.39,13.5,14.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,332.0,338.0,327.0,333.1,0.48,37561.0,12502148.0,2026,NaN,NaN,NaN,NaN
719,2026-02-25,333.0,337.0,331.1,335.0,0.57,24261.0,8113726.7,2026,NaN,NaN,NaN,NaN
720,2026-02-26,341.7,341.7,332.1,333.0,-0.60,34106.0,11393860.2,2026,NaN,NaN,NaN,NaN
721,2026-03-01,333.0,338.7,328.0,335.0,0.60,71245.0,23864542.7,2026,NaN,NaN,NaN,NaN
722,2026-03-03,340.0,341.0,335.0,341.0,1.79,53698.0,18182155.0,2026,NaN,NaN,NaN,NaN

In [11]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/SANIMA.csv', index = False)