In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/SBL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2011-06-02,231.0,227.0,215.0,216.0,NaN,1244.0,270378.0,0
1,2011-06-05,216.0,216.0,210.0,212.0,-1.85,756.0,161420.0,0
2,2011-06-06,212.0,209.0,204.0,208.0,-1.89,556.0,114958.0,0
3,2011-06-07,208.0,205.0,196.0,201.0,-3.37,1083.0,216121.0,0
4,2011-06-08,201.0,200.0,197.0,200.0,-0.50,834.0,165224.0,0
...,...,...,...,...,...,...,...,...,...
3225,2026-02-24,372.0,378.0,370.0,375.0,0.35,61772.0,22957304.1,1
3226,2026-02-25,380.0,380.0,375.0,376.5,0.40,28953.0,10912919.8,-1
3227,2026-02-26,384.0,384.0,375.0,376.0,-0.13,34496.0,13008767.8,-1
3228,2026-03-01,372.1,390.0,370.5,381.8,1.54,67247.0,25631978.4,1
3229,2026-03-03,389.4,389.4,381.8,386.4,1.20,90817.0,34818531.7,-1

In [3]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [4]:
df.drop(columns = 'status', inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2011-06-02,231.0,227.0,215.0,216.0,NaN,1244.0,270378.0
1,2011-06-05,216.0,216.0,210.0,212.0,-1.85,756.0,161420.0
2,2011-06-06,212.0,209.0,204.0,208.0,-1.89,556.0,114958.0
3,2011-06-07,208.0,205.0,196.0,201.0,-3.37,1083.0,216121.0
4,2011-06-08,201.0,200.0,197.0,200.0,-0.50,834.0,165224.0
...,...,...,...,...,...,...,...,...
3225,2026-02-24,372.0,378.0,370.0,375.0,0.35,61772.0,22957304.1
3226,2026-02-25,380.0,380.0,375.0,376.5,0.40,28953.0,10912919.8
3227,2026-02-26,384.0,384.0,375.0,376.0,-0.13,34496.0,13008767.8
3228,2026-03-01,372.1,390.0,370.5,381.8,1.54,67247.0,25631978.4
3229,2026-03-03,389.4,389.4,381.8,386.4,1.20,90817.0,34818531.7

In [5]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [6]:
#filtering the data from 2022 to 2025
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2507,2023-01-01,302.0,304.1,296.0,297.0,-1.66,45032.0,13499031.4,2023
2508,2023-01-02,300.0,302.0,297.0,297.3,0.10,35179.0,10541623.8,2023
2509,2023-01-03,300.0,302.0,296.0,298.0,0.24,40533.0,12121350.7,2023
2510,2023-01-04,300.0,303.0,297.1,303.0,1.68,56117.0,16831884.2,2023
2511,2023-01-05,304.0,309.0,299.0,300.0,-0.99,59839.0,18119846.6,2023
...,...,...,...,...,...,...,...,...,...
3225,2026-02-24,372.0,378.0,370.0,375.0,0.35,61772.0,22957304.1,2026
3226,2026-02-25,380.0,380.0,375.0,376.5,0.40,28953.0,10912919.8,2026
3227,2026-02-26,384.0,384.0,375.0,376.0,-0.13,34496.0,13008767.8,2026
3228,2026-03-01,372.1,390.0,370.5,381.8,1.54,67247.0,25631978.4,2026
3229,2026-03-03,389.4,389.4,381.8,386.4,1.20,90817.0,34818531.7,2026

In [8]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,302.0,304.1,296.0,297.0,-1.66,45032.0,13499031.4,2023
1,2023-01-02,300.0,302.0,297.0,297.3,0.10,35179.0,10541623.8,2023
2,2023-01-03,300.0,302.0,296.0,298.0,0.24,40533.0,12121350.7,2023
3,2023-01-04,300.0,303.0,297.1,303.0,1.68,56117.0,16831884.2,2023
4,2023-01-05,304.0,309.0,299.0,300.0,-0.99,59839.0,18119846.6,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,372.0,378.0,370.0,375.0,0.35,61772.0,22957304.1,2026
719,2026-02-25,380.0,380.0,375.0,376.5,0.40,28953.0,10912919.8,2026
720,2026-02-26,384.0,384.0,375.0,376.0,-0.13,34496.0,13008767.8,2026
721,2026-03-01,372.1,390.0,370.5,381.8,1.54,67247.0,25631978.4,2026
722,2026-03-03,389.4,389.4,381.8,386.4,1.20,90817.0,34818531.7,2026

In [9]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # FY 78/79, 79/80, 80/81, 81/82
    'eps': [21.80, 18.25, 12.45, 17.93],   # NPR (Annualized EPS)
    'pe-ratio': [14.20, 15.50, 24.60, 18.55], # Market price vs earnings
    'roe': [13.20, 11.50, 7.80, 13.96],    # Return on Equity (%)
    'dividend': [13.16, 4.21, 4.00, 10.53],# Total % (Bonus + Cash)
    'net-margin': [24.10, 21.20, 14.80, 22.40], # (%)
    'pb-ratio': [1.55, 1.45, 1.65, 1.87],      # Price-to-Book Ratio
    'debt-equity': [8.40, 8.65, 9.10, 8.95]}   # Bank leverage (Assets/Equity)

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  21.80     14.20  13.20     13.16        24.1      1.55         8.40
1  2023  18.25     15.50  11.50      4.21        21.2      1.45         8.65
2  2024  12.45     24.60   7.80      4.00        14.8      1.65         9.10
3  2025  17.93     18.55  13.96     10.53        22.4      1.87         8.95

In [10]:

# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2023-01-01,302.0,304.1,296.0,297.0,-1.66,45032.0,13499031.4,2023,18.25,15.5,11.5,4.21,21.2,1.45,8.65
1,2023-01-02,300.0,302.0,297.0,297.3,0.10,35179.0,10541623.8,2023,18.25,15.5,11.5,4.21,21.2,1.45,8.65
2,2023-01-03,300.0,302.0,296.0,298.0,0.24,40533.0,12121350.7,2023,18.25,15.5,11.5,4.21,21.2,1.45,8.65
3,2023-01-04,300.0,303.0,297.1,303.0,1.68,56117.0,16831884.2,2023,18.25,15.5,11.5,4.21,21.2,1.45,8.65
4,2023-01-05,304.0,309.0,299.0,300.0,-0.99,59839.0,18119846.6,2023,18.25,15.5,11.5,4.21,21.2,1.45,8.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,372.0,378.0,370.0,375.0,0.35,61772.0,22957304.1,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,2026-02-25,380.0,380.0,375.0,376.5,0.40,28953.0,10912919.8,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,2026-02-26,384.0,384.0,375.0,376.0,-0.13,34496.0,13008767.8,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,2026-03-01,372.1,390.0,370.5,381.8,1.54,67247.0,25631978.4,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,2026-03-03,389.4,389.4,381.8,386.4,1.20,90817.0,34818531.7,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/SBL.csv', index = False)