In [15]:
#importing the pandas library
import pandas as pd

In [16]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/SHEL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2021-07-05,398.0,410.0,398.0,404.0,-0.49,4652.0,1867603.0,-1
1,2021-07-06,397.0,413.0,396.0,399.0,-1.24,5470.0,2195355.0,-1
2,2021-07-07,393.0,405.0,392.0,394.0,-1.25,4523.0,1787768.0,-1
3,2021-07-08,375.0,404.0,375.0,397.0,0.76,9432.0,3749118.0,1
4,2021-07-11,397.0,405.0,397.0,404.0,1.76,7190.0,2883995.0,1
...,...,...,...,...,...,...,...,...,...
1075,2026-02-24,288.2,299.8,288.2,298.0,1.36,116070.0,34449720.2,1
1076,2026-02-25,294.4,302.9,294.4,299.0,0.34,173991.0,52127458.1,1
1077,2026-02-26,299.0,301.9,296.7,298.7,-0.10,123869.0,36933936.8,-1
1078,2026-03-01,296.5,301.5,284.5,300.0,0.44,174683.0,52165058.5,1
1079,2026-03-03,294.0,307.0,294.0,305.4,1.80,146230.0,44568247.0,1

In [17]:
#dropping the status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2021-07-05,398.0,410.0,398.0,404.0,-0.49,4652.0,1867603.0
1,2021-07-06,397.0,413.0,396.0,399.0,-1.24,5470.0,2195355.0
2,2021-07-07,393.0,405.0,392.0,394.0,-1.25,4523.0,1787768.0
3,2021-07-08,375.0,404.0,375.0,397.0,0.76,9432.0,3749118.0
4,2021-07-11,397.0,405.0,397.0,404.0,1.76,7190.0,2883995.0
...,...,...,...,...,...,...,...,...
1075,2026-02-24,288.2,299.8,288.2,298.0,1.36,116070.0,34449720.2
1076,2026-02-25,294.4,302.9,294.4,299.0,0.34,173991.0,52127458.1
1077,2026-02-26,299.0,301.9,296.7,298.7,-0.10,123869.0,36933936.8
1078,2026-03-01,296.5,301.5,284.5,300.0,0.44,174683.0,52165058.5
1079,2026-03-03,294.0,307.0,294.0,305.4,1.80,146230.0,44568247.0

In [18]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [19]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2021-07-05,398.0,410.0,398.0,404.0,-0.49,4652.0,1867603.0
1,2021-07-06,397.0,413.0,396.0,399.0,-1.24,5470.0,2195355.0
2,2021-07-07,393.0,405.0,392.0,394.0,-1.25,4523.0,1787768.0
3,2021-07-08,375.0,404.0,375.0,397.0,0.76,9432.0,3749118.0
4,2021-07-11,397.0,405.0,397.0,404.0,1.76,7190.0,2883995.0
...,...,...,...,...,...,...,...,...
1075,2026-02-24,288.2,299.8,288.2,298.0,1.36,116070.0,34449720.2
1076,2026-02-25,294.4,302.9,294.4,299.0,0.34,173991.0,52127458.1
1077,2026-02-26,299.0,301.9,296.7,298.7,-0.10,123869.0,36933936.8
1078,2026-03-01,296.5,301.5,284.5,300.0,0.44,174683.0,52165058.5
1079,2026-03-03,294.0,307.0,294.0,305.4,1.80,146230.0,44568247.0

In [20]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [21]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2021-07-05,398.0,410.0,398.0,404.0,-0.49,4652.0,1867603.0,2021
1,2021-07-06,397.0,413.0,396.0,399.0,-1.24,5470.0,2195355.0,2021
2,2021-07-07,393.0,405.0,392.0,394.0,-1.25,4523.0,1787768.0,2021
3,2021-07-08,375.0,404.0,375.0,397.0,0.76,9432.0,3749118.0,2021
4,2021-07-11,397.0,405.0,397.0,404.0,1.76,7190.0,2883995.0,2021
...,...,...,...,...,...,...,...,...,...
1075,2026-02-24,288.2,299.8,288.2,298.0,1.36,116070.0,34449720.2,2026
1076,2026-02-25,294.4,302.9,294.4,299.0,0.34,173991.0,52127458.1,2026
1077,2026-02-26,299.0,301.9,296.7,298.7,-0.10,123869.0,36933936.8,2026
1078,2026-03-01,296.5,301.5,284.5,300.0,0.44,174683.0,52165058.5,2026
1079,2026-03-03,294.0,307.0,294.0,305.4,1.80,146230.0,44568247.0,2026

In [22]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [23]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
357,2023-01-01,253.9,258.0,244.2,244.2,-1.93,9961.0,2516183.0,2023
358,2023-01-02,244.0,262.1,244.0,262.0,7.29,10694.0,2736423.0,2023
359,2023-01-03,267.2,267.2,256.0,260.0,-0.76,4650.0,1216445.0,2023
360,2023-01-04,254.8,272.0,254.8,269.0,3.46,8455.0,2252001.8,2023
361,2023-01-05,263.8,282.5,263.8,270.6,0.59,9218.0,2502643.0,2023
...,...,...,...,...,...,...,...,...,...
1075,2026-02-24,288.2,299.8,288.2,298.0,1.36,116070.0,34449720.2,2026
1076,2026-02-25,294.4,302.9,294.4,299.0,0.34,173991.0,52127458.1,2026
1077,2026-02-26,299.0,301.9,296.7,298.7,-0.10,123869.0,36933936.8,2026
1078,2026-03-01,296.5,301.5,284.5,300.0,0.44,174683.0,52165058.5,2026
1079,2026-03-03,294.0,307.0,294.0,305.4,1.80,146230.0,44568247.0,2026

In [24]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,253.9,258.0,244.2,244.2,-1.93,9961.0,2516183.0,2023
1,2023-01-02,244.0,262.1,244.0,262.0,7.29,10694.0,2736423.0,2023
2,2023-01-03,267.2,267.2,256.0,260.0,-0.76,4650.0,1216445.0,2023
3,2023-01-04,254.8,272.0,254.8,269.0,3.46,8455.0,2252001.8,2023
4,2023-01-05,263.8,282.5,263.8,270.6,0.59,9218.0,2502643.0,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,288.2,299.8,288.2,298.0,1.36,116070.0,34449720.2,2026
719,2026-02-25,294.4,302.9,294.4,299.0,0.34,173991.0,52127458.1,2026
720,2026-02-26,299.0,301.9,296.7,298.7,-0.10,123869.0,36933936.8,2026
721,2026-03-01,296.5,301.5,284.5,300.0,0.44,174683.0,52165058.5,2026
722,2026-03-03,294.0,307.0,294.0,305.4,1.80,146230.0,44568247.0,2026

In [25]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025],      # FY end periods (78/79 to 81/82)
    'eps': [3.12, 4.45, 6.70, 13.58],      # NPR (Growth post-commercial operation)
    'pe-ratio': [92.0, 75.4, 47.4, 24.8],  # Valuation softening as earnings rise
    'roe': [2.85, 3.90, 6.33, 11.78],      # Return on Equity (%)
    'dividend': [0.00, 0.00, 0.00, 5.00],  # 5% Bonus Share proposed for FY 2081/82
    'net-margin': [12.4, 18.2, 24.5, 32.1], # Operational efficiency improvement
    'pb-ratio': [3.20, 3.00, 2.90, 2.93],  
    'debt-equity': [2.10, 1.85, 0.85, 0.72] # Sharp drop due to 1:1 Right Share
}

df_fundamental = pd.DataFrame(fundamental_data)
print(df_fundamental)

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022   3.12      92.0   2.85       0.0        12.4      3.20         2.10
1  2023   4.45      75.4   3.90       0.0        18.2      3.00         1.85
2  2024   6.70      47.4   6.33       0.0        24.5      2.90         0.85
3  2025  13.58      24.8  11.78       5.0        32.1      2.93         0.72

In [26]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2023-01-01,253.9,258.0,244.2,244.2,-1.93,9961.0,2516183.0,2023,4.45,75.4,3.9,0.0,18.2,3.0,1.85
1,2023-01-02,244.0,262.1,244.0,262.0,7.29,10694.0,2736423.0,2023,4.45,75.4,3.9,0.0,18.2,3.0,1.85
2,2023-01-03,267.2,267.2,256.0,260.0,-0.76,4650.0,1216445.0,2023,4.45,75.4,3.9,0.0,18.2,3.0,1.85
3,2023-01-04,254.8,272.0,254.8,269.0,3.46,8455.0,2252001.8,2023,4.45,75.4,3.9,0.0,18.2,3.0,1.85
4,2023-01-05,263.8,282.5,263.8,270.6,0.59,9218.0,2502643.0,2023,4.45,75.4,3.9,0.0,18.2,3.0,1.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,288.2,299.8,288.2,298.0,1.36,116070.0,34449720.2,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,2026-02-25,294.4,302.9,294.4,299.0,0.34,173991.0,52127458.1,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,2026-02-26,299.0,301.9,296.7,298.7,-0.10,123869.0,36933936.8,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,2026-03-01,296.5,301.5,284.5,300.0,0.44,174683.0,52165058.5,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,2026-03-03,294.0,307.0,294.0,305.4,1.80,146230.0,44568247.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/SHEL.csv', index = False)