In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/UNHPL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2019-07-24,95.0,95.0,94.0,94.0,-5.05,100.0,9450.0,-1
1,2019-07-25,90.0,90.0,85.0,85.0,-9.57,3500.0,298087.0,-1
2,2019-07-28,84.0,84.0,77.0,78.0,-8.24,821.0,63698.0,-1
3,2019-07-29,77.0,78.0,72.0,78.0,0.00,1900.0,142260.0,0
4,2019-07-30,77.0,77.0,73.0,73.0,-6.41,3410.0,252320.0,-1
...,...,...,...,...,...,...,...,...,...
1475,2026-02-24,482.0,485.3,476.0,483.0,0.63,66358.0,31974869.3,1
1476,2026-02-25,485.0,500.0,481.0,497.0,2.90,126698.0,62144457.7,1
1477,2026-02-26,490.0,505.9,490.0,496.0,-0.20,132780.0,66196728.6,1
1478,2026-03-01,486.2,499.9,486.2,495.2,-0.16,106944.0,52950945.7,1
1479,2026-03-03,490.1,500.5,490.1,496.0,0.16,122438.0,60984101.0,1

In [3]:
#dropping the status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2019-07-24,95.0,95.0,94.0,94.0,-5.05,100.0,9450.0
1,2019-07-25,90.0,90.0,85.0,85.0,-9.57,3500.0,298087.0
2,2019-07-28,84.0,84.0,77.0,78.0,-8.24,821.0,63698.0
3,2019-07-29,77.0,78.0,72.0,78.0,0.00,1900.0,142260.0
4,2019-07-30,77.0,77.0,73.0,73.0,-6.41,3410.0,252320.0
...,...,...,...,...,...,...,...,...
1475,2026-02-24,482.0,485.3,476.0,483.0,0.63,66358.0,31974869.3
1476,2026-02-25,485.0,500.0,481.0,497.0,2.90,126698.0,62144457.7
1477,2026-02-26,490.0,505.9,490.0,496.0,-0.20,132780.0,66196728.6
1478,2026-03-01,486.2,499.9,486.2,495.2,-0.16,106944.0,52950945.7
1479,2026-03-03,490.1,500.5,490.1,496.0,0.16,122438.0,60984101.0

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2019-07-24,95.0,95.0,94.0,94.0,-5.05,100.0,9450.0
1,2019-07-25,90.0,90.0,85.0,85.0,-9.57,3500.0,298087.0
2,2019-07-28,84.0,84.0,77.0,78.0,-8.24,821.0,63698.0
3,2019-07-29,77.0,78.0,72.0,78.0,0.00,1900.0,142260.0
4,2019-07-30,77.0,77.0,73.0,73.0,-6.41,3410.0,252320.0
...,...,...,...,...,...,...,...,...
1475,2026-02-24,482.0,485.3,476.0,483.0,0.63,66358.0,31974869.3
1476,2026-02-25,485.0,500.0,481.0,497.0,2.90,126698.0,62144457.7
1477,2026-02-26,490.0,505.9,490.0,496.0,-0.20,132780.0,66196728.6
1478,2026-03-01,486.2,499.9,486.2,495.2,-0.16,106944.0,52950945.7
1479,2026-03-03,490.1,500.5,490.1,496.0,0.16,122438.0,60984101.0

In [6]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2019-07-24,95.0,95.0,94.0,94.0,-5.05,100.0,9450.0,2019
1,2019-07-25,90.0,90.0,85.0,85.0,-9.57,3500.0,298087.0,2019
2,2019-07-28,84.0,84.0,77.0,78.0,-8.24,821.0,63698.0,2019
3,2019-07-29,77.0,78.0,72.0,78.0,0.00,1900.0,142260.0,2019
4,2019-07-30,77.0,77.0,73.0,73.0,-6.41,3410.0,252320.0,2019
...,...,...,...,...,...,...,...,...,...
1475,2026-02-24,482.0,485.3,476.0,483.0,0.63,66358.0,31974869.3,2026
1476,2026-02-25,485.0,500.0,481.0,497.0,2.90,126698.0,62144457.7,2026
1477,2026-02-26,490.0,505.9,490.0,496.0,-0.20,132780.0,66196728.6,2026
1478,2026-03-01,486.2,499.9,486.2,495.2,-0.16,106944.0,52950945.7,2026
1479,2026-03-03,490.1,500.5,490.1,496.0,0.16,122438.0,60984101.0,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
757,2023-01-01,208.8,213.0,198.9,202.0,-1.37,66352.0,13696986.2,2023
758,2023-01-02,202.0,214.0,198.0,212.0,4.95,91118.0,19087461.0,2023
759,2023-01-03,212.0,219.0,209.0,215.0,1.42,83624.0,17938464.4,2023
760,2023-01-04,215.0,227.7,214.8,226.0,5.12,60373.0,13308046.3,2023
761,2023-01-05,230.2,235.5,223.1,227.0,0.44,35466.0,8152164.9,2023
...,...,...,...,...,...,...,...,...,...
1475,2026-02-24,482.0,485.3,476.0,483.0,0.63,66358.0,31974869.3,2026
1476,2026-02-25,485.0,500.0,481.0,497.0,2.90,126698.0,62144457.7,2026
1477,2026-02-26,490.0,505.9,490.0,496.0,-0.20,132780.0,66196728.6,2026
1478,2026-03-01,486.2,499.9,486.2,495.2,-0.16,106944.0,52950945.7,2026
1479,2026-03-03,490.1,500.5,490.1,496.0,0.16,122438.0,60984101.0,2026

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,208.8,213.0,198.9,202.0,-1.37,66352.0,13696986.2,2023
1,2023-01-02,202.0,214.0,198.0,212.0,4.95,91118.0,19087461.0,2023
2,2023-01-03,212.0,219.0,209.0,215.0,1.42,83624.0,17938464.4,2023
3,2023-01-04,215.0,227.7,214.8,226.0,5.12,60373.0,13308046.3,2023
4,2023-01-05,230.2,235.5,223.1,227.0,0.44,35466.0,8152164.9,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,482.0,485.3,476.0,483.0,0.63,66358.0,31974869.3,2026
719,2026-02-25,485.0,500.0,481.0,497.0,2.90,126698.0,62144457.7,2026
720,2026-02-26,490.0,505.9,490.0,496.0,-0.20,132780.0,66196728.6,2026
721,2026-03-01,486.2,499.9,486.2,495.2,-0.16,106944.0,52950945.7,2026
722,2026-03-03,490.1,500.5,490.1,496.0,0.16,122438.0,60984101.0,2026

In [11]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [0.45, 0.82, 1.15, 2.66],
    'pe-ratio': [450.20, 280.40, 210.50, 191.74],
    'roe': [0.42, 0.78, 1.12, 2.63],
    'dividend': [0.00, 0.00, 0.00, 0.00]}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year   eps  pe-ratio   roe  dividend
0  2022  0.45    450.20  0.42       0.0
1  2023  0.82    280.40  0.78       0.0
2  2024  1.15    210.50  1.12       0.0
3  2025  2.66    191.74  2.63       0.0

In [12]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2023-01-01,208.8,213.0,198.9,202.0,-1.37,66352.0,13696986.2,2023,0.82,280.4,0.78,0.0
1,2023-01-02,202.0,214.0,198.0,212.0,4.95,91118.0,19087461.0,2023,0.82,280.4,0.78,0.0
2,2023-01-03,212.0,219.0,209.0,215.0,1.42,83624.0,17938464.4,2023,0.82,280.4,0.78,0.0
3,2023-01-04,215.0,227.7,214.8,226.0,5.12,60373.0,13308046.3,2023,0.82,280.4,0.78,0.0
4,2023-01-05,230.2,235.5,223.1,227.0,0.44,35466.0,8152164.9,2023,0.82,280.4,0.78,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,482.0,485.3,476.0,483.0,0.63,66358.0,31974869.3,2026,NaN,NaN,NaN,NaN
719,2026-02-25,485.0,500.0,481.0,497.0,2.90,126698.0,62144457.7,2026,NaN,NaN,NaN,NaN
720,2026-02-26,490.0,505.9,490.0,496.0,-0.20,132780.0,66196728.6,2026,NaN,NaN,NaN,NaN
721,2026-03-01,486.2,499.9,486.2,495.2,-0.16,106944.0,52950945.7,2026,NaN,NaN,NaN,NaN
722,2026-03-03,490.1,500.5,490.1,496.0,0.16,122438.0,60984101.0,2026,NaN,NaN,NaN,NaN

In [13]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/UNHPL.csv', index = False)