In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/UPCL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2019-05-21,91.0,97.0,91.0,95.0,3.26,14515.0,1368205.0,1
1,2019-05-22,96.0,102.0,96.0,100.0,5.26,51310.0,5040190.0,1
2,2019-05-23,98.0,102.0,94.0,96.0,-4.00,20010.0,1941570.0,-1
3,2019-05-26,96.0,96.0,94.0,96.0,0.00,6955.0,659760.0,0
4,2019-05-27,96.0,96.0,94.0,94.0,-2.08,3692.0,350186.0,-1
...,...,...,...,...,...,...,...,...,...
1525,2026-02-24,368.0,371.0,364.0,369.1,1.40,73381.0,27058356.8,1
1526,2026-02-25,367.5,375.0,365.0,367.2,-0.51,88711.0,32789265.8,-1
1527,2026-02-26,371.0,373.0,366.0,367.2,0.00,28310.0,10425003.6,-1
1528,2026-03-01,374.5,374.5,360.5,367.9,0.19,60291.0,22051068.9,-1
1529,2026-03-03,360.7,380.3,360.7,378.5,2.88,111888.0,42168187.9,1

In [3]:
#dropping the status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2019-05-21,91.0,97.0,91.0,95.0,3.26,14515.0,1368205.0
1,2019-05-22,96.0,102.0,96.0,100.0,5.26,51310.0,5040190.0
2,2019-05-23,98.0,102.0,94.0,96.0,-4.00,20010.0,1941570.0
3,2019-05-26,96.0,96.0,94.0,96.0,0.00,6955.0,659760.0
4,2019-05-27,96.0,96.0,94.0,94.0,-2.08,3692.0,350186.0
...,...,...,...,...,...,...,...,...
1525,2026-02-24,368.0,371.0,364.0,369.1,1.40,73381.0,27058356.8
1526,2026-02-25,367.5,375.0,365.0,367.2,-0.51,88711.0,32789265.8
1527,2026-02-26,371.0,373.0,366.0,367.2,0.00,28310.0,10425003.6
1528,2026-03-01,374.5,374.5,360.5,367.9,0.19,60291.0,22051068.9
1529,2026-03-03,360.7,380.3,360.7,378.5,2.88,111888.0,42168187.9

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2019-05-21,91.0,97.0,91.0,95.0,3.26,14515.0,1368205.0
1,2019-05-22,96.0,102.0,96.0,100.0,5.26,51310.0,5040190.0
2,2019-05-23,98.0,102.0,94.0,96.0,-4.00,20010.0,1941570.0
3,2019-05-26,96.0,96.0,94.0,96.0,0.00,6955.0,659760.0
4,2019-05-27,96.0,96.0,94.0,94.0,-2.08,3692.0,350186.0
...,...,...,...,...,...,...,...,...
1525,2026-02-24,368.0,371.0,364.0,369.1,1.40,73381.0,27058356.8
1526,2026-02-25,367.5,375.0,365.0,367.2,-0.51,88711.0,32789265.8
1527,2026-02-26,371.0,373.0,366.0,367.2,0.00,28310.0,10425003.6
1528,2026-03-01,374.5,374.5,360.5,367.9,0.19,60291.0,22051068.9
1529,2026-03-03,360.7,380.3,360.7,378.5,2.88,111888.0,42168187.9

In [6]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2019-05-21,91.0,97.0,91.0,95.0,3.26,14515.0,1368205.0,2019
1,2019-05-22,96.0,102.0,96.0,100.0,5.26,51310.0,5040190.0,2019
2,2019-05-23,98.0,102.0,94.0,96.0,-4.00,20010.0,1941570.0,2019
3,2019-05-26,96.0,96.0,94.0,96.0,0.00,6955.0,659760.0,2019
4,2019-05-27,96.0,96.0,94.0,94.0,-2.08,3692.0,350186.0,2019
...,...,...,...,...,...,...,...,...,...
1525,2026-02-24,368.0,371.0,364.0,369.1,1.40,73381.0,27058356.8,2026
1526,2026-02-25,367.5,375.0,365.0,367.2,-0.51,88711.0,32789265.8,2026
1527,2026-02-26,371.0,373.0,366.0,367.2,0.00,28310.0,10425003.6,2026
1528,2026-03-01,374.5,374.5,360.5,367.9,0.19,60291.0,22051068.9,2026
1529,2026-03-03,360.7,380.3,360.7,378.5,2.88,111888.0,42168187.9,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
807,2023-01-01,238.0,243.3,233.0,237.4,1.71,234115.0,55777283.6,2023
808,2023-01-02,237.0,255.0,234.0,254.0,6.99,318763.0,79234040.3,2023
809,2023-01-03,256.9,257.0,243.4,246.0,-3.15,173844.0,43261411.3,2023
810,2023-01-04,248.0,260.0,244.0,256.0,4.07,221654.0,55813782.7,2023
811,2023-01-05,261.1,261.1,249.0,253.3,-1.05,169256.0,42940850.7,2023
...,...,...,...,...,...,...,...,...,...
1525,2026-02-24,368.0,371.0,364.0,369.1,1.40,73381.0,27058356.8,2026
1526,2026-02-25,367.5,375.0,365.0,367.2,-0.51,88711.0,32789265.8,2026
1527,2026-02-26,371.0,373.0,366.0,367.2,0.00,28310.0,10425003.6,2026
1528,2026-03-01,374.5,374.5,360.5,367.9,0.19,60291.0,22051068.9,2026
1529,2026-03-03,360.7,380.3,360.7,378.5,2.88,111888.0,42168187.9,2026

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,238.0,243.3,233.0,237.4,1.71,234115.0,55777283.6,2023
1,2023-01-02,237.0,255.0,234.0,254.0,6.99,318763.0,79234040.3,2023
2,2023-01-03,256.9,257.0,243.4,246.0,-3.15,173844.0,43261411.3,2023
3,2023-01-04,248.0,260.0,244.0,256.0,4.07,221654.0,55813782.7,2023
4,2023-01-05,261.1,261.1,249.0,253.3,-1.05,169256.0,42940850.7,2023
...,...,...,...,...,...,...,...,...,...
718,2026-02-24,368.0,371.0,364.0,369.1,1.40,73381.0,27058356.8,2026
719,2026-02-25,367.5,375.0,365.0,367.2,-0.51,88711.0,32789265.8,2026
720,2026-02-26,371.0,373.0,366.0,367.2,0.00,28310.0,10425003.6,2026
721,2026-03-01,374.5,374.5,360.5,367.9,0.19,60291.0,22051068.9,2026
722,2026-03-03,360.7,380.3,360.7,378.5,2.88,111888.0,42168187.9,2026

In [11]:
import pandas as pd

# Precise Fundamental Data for UPCL (Universal Power Company Ltd)
# Calculated based on Audited Q4 Reports and Year-End Closing Prices
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # FY 78/79 to 81/82
    'eps': [0.12, 1.34, 4.41, 6.74],      # NPR (Audited & 2025 Q2 Annualized)
    'pe-ratio': [1825.0, 172.38, 48.07, 54.48], # Based on price volatility (Current ~367)
    'roe': [0.11, 1.25, 4.12, 4.53],      # Return on Equity (%)
    'dividend': [0.00, 8.55, 0.00, 9.47]} # TOTAL % (Bonus + Cash for tax)

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year   eps  pe-ratio   roe  dividend
0  2022  0.12   1825.00  0.11      0.00
1  2023  1.34    172.38  1.25      8.55
2  2024  4.41     48.07  4.12      0.00
3  2025  6.74     54.48  4.53      9.47

In [12]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2023-01-01,238.0,243.3,233.0,237.4,1.71,234115.0,55777283.6,2023,1.34,172.38,1.25,8.55
1,2023-01-02,237.0,255.0,234.0,254.0,6.99,318763.0,79234040.3,2023,1.34,172.38,1.25,8.55
2,2023-01-03,256.9,257.0,243.4,246.0,-3.15,173844.0,43261411.3,2023,1.34,172.38,1.25,8.55
3,2023-01-04,248.0,260.0,244.0,256.0,4.07,221654.0,55813782.7,2023,1.34,172.38,1.25,8.55
4,2023-01-05,261.1,261.1,249.0,253.3,-1.05,169256.0,42940850.7,2023,1.34,172.38,1.25,8.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2026-02-24,368.0,371.0,364.0,369.1,1.40,73381.0,27058356.8,2026,NaN,NaN,NaN,NaN
719,2026-02-25,367.5,375.0,365.0,367.2,-0.51,88711.0,32789265.8,2026,NaN,NaN,NaN,NaN
720,2026-02-26,371.0,373.0,366.0,367.2,0.00,28310.0,10425003.6,2026,NaN,NaN,NaN,NaN
721,2026-03-01,374.5,374.5,360.5,367.9,0.19,60291.0,22051068.9,2026,NaN,NaN,NaN,NaN
722,2026-03-03,360.7,380.3,360.7,378.5,2.88,111888.0,42168187.9,2026,NaN,NaN,NaN,NaN

In [13]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/UPCL.csv', index = False)