In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/processed_data/UPCL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2019-05-21,91.0,97.0,91.0,95.0,3.26,14515.0,1368205.0,1
1,2019-05-22,96.0,102.0,96.0,100.0,5.26,51310.0,5040190.0,1
2,2019-05-23,98.0,102.0,94.0,96.0,-4.00,20010.0,1941570.0,-1
3,2019-05-26,96.0,96.0,94.0,96.0,0.00,6955.0,659760.0,0
4,2019-05-27,96.0,96.0,94.0,94.0,-2.08,3692.0,350186.0,-1
...,...,...,...,...,...,...,...,...,...
1507,2026-01-26,386.7,386.7,375.4,383.0,1.00,291373.0,110974855.0,-1
1508,2026-01-27,383.1,405.0,381.0,389.9,1.80,538440.0,212416980.6,1
1509,2026-01-28,394.0,398.0,382.2,395.0,1.31,338745.0,132327139.7,1
1510,2026-01-29,387.1,409.7,387.1,391.0,-1.01,504046.0,201213322.2,1
1511,2026-02-01,394.8,394.8,378.1,379.0,-3.07,124301.0,47586218.6,-1

In [3]:
#dropping the status column
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2019-05-21,91.0,97.0,91.0,95.0,3.26,14515.0,1368205.0
1,2019-05-22,96.0,102.0,96.0,100.0,5.26,51310.0,5040190.0
2,2019-05-23,98.0,102.0,94.0,96.0,-4.00,20010.0,1941570.0
3,2019-05-26,96.0,96.0,94.0,96.0,0.00,6955.0,659760.0
4,2019-05-27,96.0,96.0,94.0,94.0,-2.08,3692.0,350186.0
...,...,...,...,...,...,...,...,...
1507,2026-01-26,386.7,386.7,375.4,383.0,1.00,291373.0,110974855.0
1508,2026-01-27,383.1,405.0,381.0,389.9,1.80,538440.0,212416980.6
1509,2026-01-28,394.0,398.0,382.2,395.0,1.31,338745.0,132327139.7
1510,2026-01-29,387.1,409.7,387.1,391.0,-1.01,504046.0,201213322.2
1511,2026-02-01,394.8,394.8,378.1,379.0,-3.07,124301.0,47586218.6

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2019-05-21,91.0,97.0,91.0,95.0,3.26,14515.0,1368205.0
1,2019-05-22,96.0,102.0,96.0,100.0,5.26,51310.0,5040190.0
2,2019-05-23,98.0,102.0,94.0,96.0,-4.00,20010.0,1941570.0
3,2019-05-26,96.0,96.0,94.0,96.0,0.00,6955.0,659760.0
4,2019-05-27,96.0,96.0,94.0,94.0,-2.08,3692.0,350186.0
...,...,...,...,...,...,...,...,...
1507,2026-01-26,386.7,386.7,375.4,383.0,1.00,291373.0,110974855.0
1508,2026-01-27,383.1,405.0,381.0,389.9,1.80,538440.0,212416980.6
1509,2026-01-28,394.0,398.0,382.2,395.0,1.31,338745.0,132327139.7
1510,2026-01-29,387.1,409.7,387.1,391.0,-1.01,504046.0,201213322.2
1511,2026-02-01,394.8,394.8,378.1,379.0,-3.07,124301.0,47586218.6

In [6]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2019-05-21,91.0,97.0,91.0,95.0,3.26,14515.0,1368205.0,2019
1,2019-05-22,96.0,102.0,96.0,100.0,5.26,51310.0,5040190.0,2019
2,2019-05-23,98.0,102.0,94.0,96.0,-4.00,20010.0,1941570.0,2019
3,2019-05-26,96.0,96.0,94.0,96.0,0.00,6955.0,659760.0,2019
4,2019-05-27,96.0,96.0,94.0,94.0,-2.08,3692.0,350186.0,2019
...,...,...,...,...,...,...,...,...,...
1507,2026-01-26,386.7,386.7,375.4,383.0,1.00,291373.0,110974855.0,2026
1508,2026-01-27,383.1,405.0,381.0,389.9,1.80,538440.0,212416980.6,2026
1509,2026-01-28,394.0,398.0,382.2,395.0,1.31,338745.0,132327139.7,2026
1510,2026-01-29,387.1,409.7,387.1,391.0,-1.01,504046.0,201213322.2,2026
1511,2026-02-01,394.8,394.8,378.1,379.0,-3.07,124301.0,47586218.6,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year.between(2022, 2025)].copy()

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
565,2022-01-02,349.8,356.7,340.0,343.0,0.00,37079.0,12802015.7,2022
566,2022-01-03,349.0,355.0,343.5,344.0,0.29,36798.0,12832805.1,2022
567,2022-01-04,350.0,360.0,343.0,357.0,3.78,44737.0,15748504.1,2022
568,2022-01-05,362.0,372.4,351.0,361.0,1.12,80418.0,29302836.0,2022
569,2022-01-06,361.0,367.2,356.0,366.1,1.41,52079.0,18913909.9,2022
...,...,...,...,...,...,...,...,...,...
1488,2025-12-23,362.5,362.5,358.0,361.0,0.03,78905.0,28357398.5,2025
1489,2025-12-24,360.2,365.0,358.0,359.0,-0.55,85232.0,30703064.6,2025
1490,2025-12-28,366.1,368.6,360.0,368.0,2.51,114968.0,41941232.2,2025
1491,2025-12-29,370.0,370.0,360.2,365.8,-0.60,80686.0,29374711.3,2025
1492,2025-12-31,364.0,367.9,362.0,362.5,-0.90,67879.0,24770077.7,2025

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,349.8,356.7,340.0,343.0,0.00,37079.0,12802015.7,2022
1,2022-01-03,349.0,355.0,343.5,344.0,0.29,36798.0,12832805.1,2022
2,2022-01-04,350.0,360.0,343.0,357.0,3.78,44737.0,15748504.1,2022
3,2022-01-05,362.0,372.4,351.0,361.0,1.12,80418.0,29302836.0,2022
4,2022-01-06,361.0,367.2,356.0,366.1,1.41,52079.0,18913909.9,2022
...,...,...,...,...,...,...,...,...,...
923,2025-12-23,362.5,362.5,358.0,361.0,0.03,78905.0,28357398.5,2025
924,2025-12-24,360.2,365.0,358.0,359.0,-0.55,85232.0,30703064.6,2025
925,2025-12-28,366.1,368.6,360.0,368.0,2.51,114968.0,41941232.2,2025
926,2025-12-29,370.0,370.0,360.2,365.8,-0.60,80686.0,29374711.3,2025
927,2025-12-31,364.0,367.9,362.0,362.5,-0.90,67879.0,24770077.7,2025

In [11]:
import pandas as pd

# Precise Fundamental Data for UPCL (Universal Power Company Ltd)
# Calculated based on Audited Q4 Reports and Year-End Closing Prices
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # FY 78/79 to 81/82
    'eps': [0.12, 1.34, 4.41, 6.74],      # NPR (Audited & 2025 Q2 Annualized)
    'pe-ratio': [1825.0, 172.38, 48.07, 54.48], # Based on price volatility (Current ~367)
    'roe': [0.11, 1.25, 4.12, 4.53],      # Return on Equity (%)
    'dividend': [0.00, 8.55, 0.00, 9.47]} # TOTAL % (Bonus + Cash for tax)

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year   eps  pe-ratio   roe  dividend
0  2022  0.12   1825.00  0.11      0.00
1  2023  1.34    172.38  1.25      8.55
2  2024  4.41     48.07  4.12      0.00
3  2025  6.74     54.48  4.53      9.47

In [12]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2022-01-02,349.8,356.7,340.0,343.0,0.00,37079.0,12802015.7,2022,0.12,1825.00,0.11,0.00
1,2022-01-03,349.0,355.0,343.5,344.0,0.29,36798.0,12832805.1,2022,0.12,1825.00,0.11,0.00
2,2022-01-04,350.0,360.0,343.0,357.0,3.78,44737.0,15748504.1,2022,0.12,1825.00,0.11,0.00
3,2022-01-05,362.0,372.4,351.0,361.0,1.12,80418.0,29302836.0,2022,0.12,1825.00,0.11,0.00
4,2022-01-06,361.0,367.2,356.0,366.1,1.41,52079.0,18913909.9,2022,0.12,1825.00,0.11,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,2025-12-23,362.5,362.5,358.0,361.0,0.03,78905.0,28357398.5,2025,6.74,54.48,4.53,9.47
924,2025-12-24,360.2,365.0,358.0,359.0,-0.55,85232.0,30703064.6,2025,6.74,54.48,4.53,9.47
925,2025-12-28,366.1,368.6,360.0,368.0,2.51,114968.0,41941232.2,2025,6.74,54.48,4.53,9.47
926,2025-12-29,370.0,370.0,360.2,365.8,-0.60,80686.0,29374711.3,2025,6.74,54.48,4.53,9.47
927,2025-12-31,364.0,367.9,362.0,362.5,-0.90,67879.0,24770077.7,2025,6.74,54.48,4.53,9.47

In [13]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/UPCL.csv', index = False)